# Lab 1 – Basic NumPy Operations

In [24]:
import numpy as np

## Part A - Create a Notebook to demonstrate NumPy Operations

1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

Array sequences can be generated using the numpy.arange() method, with the first argument being the number the array starts at, the second argument being the largest value that the elements of the array can be without going over, and the third argument being the incremental value that the next element of the array increases by.

In [25]:
arrayOfInts = np.arange(1, 20, 3)
print("Array of integers between 1 and 20 incrementing by 3:")
print(arrayOfInts)

Array of integers between 1 and 20 incrementing by 3:
[ 1  4  7 10 13 16 19]


2. Create a new array of shape 3 with random numbers between 0 and 1.

Random numbers can be generated using the numpy.random.rand(n) method.  The method will produce an array of size n of values between 0 and 1.

In [26]:
randomArray = np.random.rand(3)
print("Array of three random numbers between 0 and 1:")
print(randomArray)

Array of three random numbers between 0 and 1:
[0.86350301 0.92457808 0.42801118]


3. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
   * Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

nd-arrays can be sliced by adding [m:n, p:q] to the end of the array, where m:n are the start and endpoints of the rows you want to slice and p:q are the start and endpoints of the columns you want to slice.  As seen below, a shorthand can be used by leaving a number blank, which the interpreter will read as starting from the first element or ending at the last element, depending on which position is left blank.

In [27]:
ndArray1 = np.array([[10,20,45], [30,12,16], [42,17,56]])

print("Original Array:")
print(ndArray1)
print()
print("First Two Rows:")
print(ndArray1[:2,])
print()
print("Last Two Rows:")
print(ndArray1[1:,])

Original Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

First Two Rows:
[[10 20 45]
 [30 12 16]]

Last Two Rows:
[[30 12 16]
 [42 17 56]]


4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

Matricies in Python can be stacked vertically or horizontally by using the numpy.vstack(M1, M2) and numpy.hstack(M1, M2) methods respectively.  If M1 and M2 are both 2x2 matricies:
* numpy.vstack(M1, M2) will stack the matricies vertically with M1 on the top and M2 on the bottom to produce a 4x2 matrix.
* numpy.hstack(M1, M2) will stack the matricies horizontally with M1 on the left and M2 on the right to produce a 2x4 matrix.

In [28]:
array1234 = np.array([[1,2],
                      [3,4]])
array5678 = np.array([[5,6],
                      [7,8]])
vertArray = np.vstack([array1234, array5678])
horArray = np.hstack([array1234, array5678])
print("Array 1:")
print(array1234)
print()
print("Array 2:")
print(array5678)
print()
print("Vertical Stack:")
print(vertArray)
print()
print("Horizontal Stack:")
print(horArray)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


5. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
   * Is it possible to multiply these matrices?
   * Demonstrate the case when it is not possible to.

Two matricies with (n,m) dimensions and (p,q) dimensions respectively can be multiplied when m = p to produce an n,q dimension matrix.  Since matrix X is 3x3 and matrix Y is 3x2, they can be multiplied to make a 3x2 matrix.

In [29]:
X = np.matrix([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.matrix([[4, 2], [6, 2], [4, 2]])

print("Matrix X (3x3):")
print(X)
print()
print("Matrix Y (3x2):")
print(Y)
print()
print("Matrix X*Y (3x2):")
try:
    print(X @ Y)
except ValueError:
    print("ERROR: the columns in X and the rows in Y must have equal length!")

Matrix X (3x3):
[[5 7 2]
 [4 5 6]
 [7 4 2]]

Matrix Y (3x2):
[[4 2]
 [6 2]
 [4 2]]

Matrix X*Y (3x2):
[[70 28]
 [70 30]
 [60 26]]


Two matricies cannot be multiplied together when $m \ne p$.  To demonstrate this, we will reduce Y to be a 2x2 matrix and try multiplying X by Y.

In [30]:
Y = Y[:2,]

print("Matrix X (3x3):")
print(X)
print()
print("Matrix Y (2x2):")
print(Y)
print()
print("Matrix X*Y (Should Fail):")
try:
    print(X @ Y)
except ValueError:
    print("ERROR: the columns in X and the rows in Y must have equal length!")


Matrix X (3x3):
[[5 7 2]
 [4 5 6]
 [7 4 2]]

Matrix Y (2x2):
[[4 2]
 [6 2]]

Matrix X*Y (Should Fail):
ERROR: the columns in X and the rows in Y must have equal length!


6. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
   * Find the Shape, Number of dimensions of vector x.
   * Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

The shape and dimensions of a matrix can be found using the .shape() and .ndim() methods.  To alter the shape of a matrix, we can use numpy.reshape(m, n).  Note that in order for the matrix to be reshaped, the total number of elements in the matrix must be equal to m * n.

In [31]:
x = np.array([2, -1, -8]) 
y = np.array([3, 1, -2])

print("Attributes of x:")
print(x)
print("Shape: ", x.shape)
print("Number of Dimensions: ", x.ndim)
print()
print("x Reshaped:")
print(np.reshape(x, (3,1)))
print()

yNew = np.reshape(y, (3,1))
print("Attributes of y Reshaped:")
print(yNew)
print("Shape: ", yNew.shape)
print("Number of Dimensions: ", yNew.ndim)

Attributes of x:
[ 2 -1 -8]
Shape:  (3,)
Number of Dimensions:  1

x Reshaped:
[[ 2]
 [-1]
 [-8]]

Attributes of y Reshaped:
[[ 3]
 [ 1]
 [-2]]
Shape:  (3, 1)
Number of Dimensions:  2


## Part B: Linear Equations

### Part B.1
Since the system will make a 3x3 matrix and each equation does not appear to be a linear combination of the others, I expect the system to be non-singular with a unique solution.

In [32]:
coefMatrixB1 = np.matrix([[4,  1, -2],
                          [2, -3,  2],
                          [1,  2,  3]])
depVarsB1 = np.array([10, -4, 6])
try:
    solutionB1 = np.linalg.solve(coefMatrixB1, depVarsB1)
    print("[x, y, z] = ", solutionB1)
except:
    print("The system cannot be solved with numpy functions")

[x, y, z] =  [ 1.8  2.4 -0.2]


### Part B.2
Looking at the first two equations, I can see that the second equation is simply two times the first equation.  This will make the system singular, and thus this system is not solvable using numpy functions.

In [33]:
coefMatrixB2 = np.matrix([[2, -1,  3, 4],
                          [4, -2,  6, 8],
                          [3,  1, -2, 2],
                          [1,  3, -4, 1]])
depVarsB2 = np.array([10, 20, 3, -1])
try:
    solutionB2 = np.linalg.solve(coefMatrixB2, depVarsB2)
    print("[x, y, z, w] = ", solutionB2)
except:
    print("The system cannot be solved with numpy functions")

The system cannot be solved with numpy functions


It is worth noting that we can check whether these matricies are solvable using determinants.  If the determinant of a matrix is 0, then the system does not have a unique solution.  Otherwise, a unique solution should exist.  So we should expect the determinant of part B.1 to be non-zero, and the determinant of B.2 to be 0.

In [34]:
print("Determinant of matrix B.1:")
print(np.linalg.det(coefMatrixB1))
print()
print("Determinant of matrix B.2:")
print(np.linalg.det(coefMatrixB2))

Determinant of matrix B.1:
-70.00000000000003

Determinant of matrix B.2:
0.0
