
# **Lab1 Assignment**

## PART A

###  NumPy Operations :

##### A1


In [61]:
import numpy as np
#An array starting with 1 and ends at 20
array1 = np.arange(start=1, stop=20, step=3) 
print("\n", "The array is : ")
print(array1)


 The array is : 
[ 1  4  7 10 13 16 19]


##### A2

In [62]:
#An array with random number wth shape 3
randomArray = np.random.rand(3,3)
print("\n", "The Random Array : ")
print(randomArray)


 The Random Array : 
[[0.49207926 0.22196532 0.03215227]
 [0.2641344  0.7049374  0.93627994]
 [0.35998908 0.15983377 0.38038106]]


##### A3

In [75]:
#2D Array
list = [[10,20,45],[30,12,16],[42,17,56]]
num =np.array(list)
#Array slicing to get the first two rows
print("Array after slicing is : ")
print(num[:2]) 

#Array slicing to get the last two rows
print("\n","Array after slicing is : ")
# print(num[1::])
print(num[1:])

Array after slicing is : 
[[10 20 45]
 [30 12 16]]

 Array after slicing is : 
[[30 12 16]
 [42 17 56]]


##### A4

In [82]:
#2 arrays arr1 and arr2
arr1 = np.array([[4,5],[2,3]])
arr2 = np.array([[8,9],[6,7]])
print("The Arrays are : ")
print(arr1,"\n\n", arr2)

#Stacking the arrays vertically
stackedArrayVertical = np.vstack((arr1, arr2))
print("\n","The Array after stacking the elements vertically : ")
print("\n", stackedArrayVertical)

#Stacking the arrays horizontally
stackedArrayHorizontal = np.hstack((arr1, arr2))
print("\n","The Array after stacking the elements horizontally : ")
print("\n", stackedArrayHorizontal)

#splitting the 2 arrays into smaller arrays
arr3= np.split(arr1,2)
print("\n","The first array after splitting : ")
print("\n", arr3)

arr4= np.split(arr2,2)
print("\n","The second array after splitting : ")
print("\n", arr4)





The Arrays are : 
[[4 5]
 [2 3]] 

 [[8 9]
 [6 7]]

 The Array after stacking the elements vertically : 

 [[4 5]
 [2 3]
 [8 9]
 [6 7]]

 The Array after stacking the elements horizontally : 

 [[4 5 8 9]
 [2 3 6 7]]

 The first array after splitting : 

 [array([[4, 5]]), array([[2, 3]])]

 The second array after splitting : 

 [array([[8, 9]]), array([[6, 7]])]


##### A5

In [41]:
#Matrix multiplication of 2 arrays num1 and num2
num1 = np.array([[5,7,2],[4,5,6],[7, 4 ,2]])
num2 = np.array([[4, 2], [6, 2], [4, 2]])
print(num1,"\n\n", num2)

result =np.dot(num1,num2)
print("\n","The matrix multiplication of arrays is :")
print("\n", result)

#Matrix multiplication of num3= np.array([[4, 2], [6, 2], [4, 2]]) and num4= np.array([[4, 2], [6, 2], [4, 2],[8,9]])) is not possible 



[[5 7 2]
 [4 5 6]
 [7 4 2]] 

 [[4 2]
 [6 2]
 [4 2]]

 The matrix multiplication of arrays is :

 [[70 28]
 [70 30]
 [60 26]]


##### A6

In [60]:
#Defining 2 arrays fistarr and secondarr
firstarr= np.array([2, -1, -8])
secondarr = np.array([3, 1, -2])
print("\n","The two arrays are :")
print(firstarr, "\n\n", secondarr)
# Finding the shape of firstarray
print("\n","The shape of array is :")
print("\n", firstarr.shape)


#Finding the dimension of firstarr
print("\n","The dimension of firstarr is :")
print(firstarr.ndim)

#reshaping the firstarray to (3,1)
newarr =firstarr.reshape(3,1)
print("\n","The reshaped array is :")
print(newarr)

#reshaping the secondarray to (3,1)
newarr1 =secondarr.reshape(3,1)
print("\n","The reshaped array is :")
print(newarr1)

#Finding the dimension of reshaped secondarray
print("\n","The dimension of secondarr is :")
print(newarr1.ndim)






 The two arrays are :
[ 2 -1 -8] 

 [ 3  1 -2]

 The shape of array is :

 (3,)

 The dimension of firstarr is :
1

 The reshaped array is :
[[ 2]
 [-1]
 [-8]]

 The reshaped array is :
[[ 3]
 [ 1]
 [-2]]

 The dimension of secondarr is :
2


##### A7

In [66]:
#Broadcasting in numpy :
#The broadcasting feature of NumPy can be used to perform operations on arrays of various shapes,and join arrays with varying dimensionality.
#NumPy handles broadcasting automatically and makes element-wise operations possible by expanding the smaller array to adopt the geometry of the larger one.

# A 3 Dimensional array 
Arr3D = np.array([[10,20,30],[50,60,80],[40,70,90]])
print("\n", "The 3D Array is :")
print(Arr3D)

#Performing scalar subtraction operation on the created 3D array 
ArrSub = Arr3D -5
print("\n","The subtracted array is : ")
print(ArrSub)

#Performing scalar multiplication operation on the created 3D array
ArrMulti = Arr3D * 2
print("\n", "The array after multiplication is :")
print(ArrMulti)





 The 3D Array is :
[[10 20 30]
 [50 60 80]
 [40 70 90]]

 The subtracted array is : 
[[ 5 15 25]
 [45 55 75]
 [35 65 85]]

 The array after multiplication is :
[[ 20  40  60]
 [100 120 160]
 [ 80 140 180]]
