Koonj Shah
8840641

# Lab 1 – Basic NumPy Operations


# Part A - Create a Notebook to demonstrate NumPy Operations


1) Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
import numpy as np

In [3]:
arrayOfInts = np.arange(1, 20, 3)
print("Array of integers between 1 and 20 incrementing by 3:")
print(arrayOfInts)

Array of integers between 1 and 20 incrementing by 3:
[ 1  4  7 10 13 16 19]


2) Create a new array of shape 3 with random numbers between 0 and 1.


In [7]:
random_Array = np.random.rand(3)
print("Array of three random numbers between 0 and 1:")
print(random_Array)

Array of three random numbers between 0 and 1:
[0.16590824 0.56134038 0.25437093]


3) Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [10]:
ndArray1 = np.array([[10,20,45], [30,12,16], [42,17,56]])

print("Original Array:")
print(ndArray1)
print()
print("First Two Rows:")
print(ndArray1[:2,])
print()
print("Last Two Rows:")
print(ndArray1[1:,])

Original Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

First Two Rows:
[[10 20 45]
 [30 12 16]]

Last Two Rows:
[[30 12 16]
 [42 17 56]]


4) Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [14]:
array1234 = np.array([[100,200],
                      [300,400]])
array5678 = np.array([[500,600],
                      [700,800]])
vertArray = np.vstack([array1234, array5678])
horArray = np.hstack([array1234, array5678])
print("Array 1:")
print(array1234)
print()
print("Array 2:")
print(array5678)
print()
print("Vertical Stack:")
print(vertArray)
print()
print("Horizontal Stack:")
print(horArray)

Array 1:
[[100 200]
 [300 400]]

Array 2:
[[500 600]
 [700 800]]

Vertical Stack:
[[100 200]
 [300 400]
 [500 600]
 [700 800]]

Horizontal Stack:
[[100 200 500 600]
 [300 400 700 800]]


5) Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]])

Is it possible to multiply these matrices?

Yes, It is possible to multiply these matrices as X has 3 columns, and Y has 3 rows, so matrix multiplication is possible.

Demonstrate the case when it is not possible to.

When the Matrix A has 3 columns, and matrix B has 3 rows. Since the number of columns in A does not match the number of rows in B, matrix multiplication is not possible for these matrices.

In [15]:
X = np.matrix([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.matrix([[4, 2], [6, 2], [4, 2]])

print("Matrix X (3x3):")
print(X)
print()
print("Matrix Y (3x2):")
print(Y)
print()
print("Matrix X*Y (3x2):")
try:
    print(X @ Y)
except ValueError:
    print("ERROR: the columns in X and the rows in Y must have equal length!")

Matrix X (3x3):
[[5 7 2]
 [4 5 6]
 [7 4 2]]

Matrix Y (3x2):
[[4 2]
 [6 2]
 [4 2]]

Matrix X*Y (3x2):
[[70 28]
 [70 30]
 [60 26]]


In [18]:
Y = Y[:2,]

print("Matrix X (3x3):")
print(X)
print()
print("Matrix Y (2x2):")
print(Y)
print()
print("Matrix X*Y (Should Fail):")
try:
    print(X @ Y)
except ValueError:
    print("ERROR: the columns in X and the rows in Y must have equal length!")

Matrix X (3x3):
[[5 7 2]
 [4 5 6]
 [7 4 2]]

Matrix Y (2x2):
[[4 2]
 [6 2]]

Matrix X*Y (Should Fail):
ERROR: the columns in X and the rows in Y must have equal length!


6) Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
Find the Shape, Number of dimensions of vector x.
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [21]:

x = np.array([2, -1, -8])
y = np.array([3, 1, -2])


shape_x = x.shape
dimensions_x = x.ndim

print("Original array x:", x)
print("Shape of x:", shape_x)
print("Number of dimensions of x:", dimensions_x)


x_reshaped = x.reshape((3, 1))


y_reshaped = y.reshape((3, 1))


dimensions_x_reshaped = x_reshaped.ndim
dimensions_y_reshaped = y_reshaped.ndim

print("\nReshaped matrix x:\n", x_reshaped)
print("Number of dimensions after reshaping x:", dimensions_x_reshaped)

print("\nReshaped matrix y:\n", y_reshaped)
print("Number of dimensions after reshaping y:", dimensions_y_reshaped)

Original array x: [ 2 -1 -8]
Shape of x: (3,)
Number of dimensions of x: 1

Reshaped matrix x:
 [[ 2]
 [-1]
 [-8]]
Number of dimensions after reshaping x: 2

Reshaped matrix y:
 [[ 3]
 [ 1]
 [-2]]
Number of dimensions after reshaping y: 2


7) How does broadcasting work? 

Broadcasting is a feature in NumPy that allows for arithmetic operations between arrays of different shapes and dimensions, under certain conditions.Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.

Lets Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [26]:

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


s_subtraction = 2


result_subtraction = matrix - s_subtraction

result_multiplication = matrix * s_subtraction

print("Original matrix:\n", matrix)
print("\nResult of subtraction:\n", result_subtraction)
print("\nResult of multiplication:\n", result_multiplication)


Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Result of subtraction:
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Result of multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Part B- Linear Equations

# Part B.1

In [27]:

matrix_b1 = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])

det_b1 = np.linalg.det(matrix_b1)

if det_b1 == 0:
    print("The coefficient matrix is singular.")
    print("The system may not have a unique solution.")
else:
    print("The coefficient matrix is not singular.")
    print("The system is expected to have a unique solution.")


The coefficient matrix is not singular.
The system is expected to have a unique solution.


Let's solve the equations as it is non singular

In [29]:

rhs = np.array([10, -4, 6])


solution = np.linalg.solve(matrix_b1, rhs)

print("\nSolution of the system:")
print("x =", solution[0])
print("y =", solution[1])
print("z =", solution[2])


Solution of the system:
x = 1.7999999999999998
y = 2.4
z = -0.2


# Part B.2

In [37]:
matrix_b2 = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])

det_b2 = np.linalg.det(matrix_b2)

if det_b2 == 0:
    print("The matrix is singular.")
    print("The system may not have a unique solution.")
else:
    print("The matrix is not singular.")
    print("The system is expected to have a unique solution.")


The matrix is singular.
The system may not have a unique solution.


In [43]:
rhs_b2 = np.array([10, 20, 3, -1])

solution_b2 = np.linalg.solve(matrix_b2, rhs_b2)

print("x =", solution_b2[0])
print("y =", solution_b2[1])
print("z =", solution_b2[2])
print("w =", solution_b2[3])

LinAlgError: Singular matrix