__Lab 1 – Basic NumPy Operations__

__Part A- Create a Notebook to demonstrate NumPy Operations.__

Import Numpy Library

In [110]:
import numpy as np

Create an array starting from 1, ending at 20, incremented by 3

In [111]:
my_array = np.arange(1, 21, 3)
print(my_array)

[ 1  4  7 10 13 16 19]


Create a new array of shape 3 with random numbers between 0 and 1

In [112]:
random_array = np.random.rand(3)
print(random_array)

[0.73602347 0.66852724 0.05716483]


Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

- Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [113]:
array_2d = np.array([[10,20,45],[30,12,16],[42,17,56]])
print(array_2d)

print("\n")
print("First 2 rows:")
print(array_2d[:2,:])
print("\n")
print("Last 2 rows:")
print(array_2d[-2:,:])


[[10 20 45]
 [30 12 16]
 [42 17 56]]


First 2 rows:
[[10 20 45]
 [30 12 16]]


Last 2 rows:
[[30 12 16]
 [42 17 56]]


Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.


In [114]:
array_1 = np.array([[2,3],[4,5]])
array_2 = np.array([[7,8],[9,10]])

vt_array = np.vstack((array_1,array_2))
print("Vertical Stack:")
print(vt_array)

print("\n")

ht_array = np.hstack((array_1,array_2))
print("Horizontal Stack:")
print(ht_array)

print("\n")

print(np.vsplit(vt_array,2))

print("\n")

print(np.hsplit(ht_array,1))

Vertical Stack:
[[ 2  3]
 [ 4  5]
 [ 7  8]
 [ 9 10]]


Horizontal Stack:
[[ 2  3  7  8]
 [ 4  5  9 10]]


[array([[2, 3],
       [4, 5]]), array([[ 7,  8],
       [ 9, 10]])]


[array([[ 2,  3,  7,  8],
       [ 4,  5,  9, 10]])]


Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),

Is it possible to multiply these matrices?

Demonstrate the case when it is not possible to

In [115]:
matrix_1 = np.array([[5,7,2],[4,5,6],[7,4,2]])
shape1 = matrix_1.shape
print("Shape of Matrix 1:",shape1)

matrix_2 = np.array([[4,2],[6,2],[4,2]])
shape2 = matrix_2.shape
print("Shape of Matrix 2:",shape2)

print("\n")
if shape1[1] == shape2[0]:
    print("Multiplication Possible")
    print("\n")
    print("Multiplication Result: \n",np.dot(matrix_1,matrix_2))

else:
    print("Multiplication Not Possible")


Shape of Matrix 1: (3, 3)
Shape of Matrix 2: (3, 2)


Multiplication Possible


Multiplication Result: 
 [[70 28]
 [70 30]
 [60 26]]


Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),

Find the Shape, Number of dimensions of vector x.

Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping to a matrix of (3,1).

In [116]:
x = np.array([2, -1, -8])
print(f"Vector X: Shape {x.shape} and Dimension {x.ndim}")

y = np.array([3, 1, -2])
print(f"Vector Y: Shape {y.shape} and Dimension {y.ndim}")

print("\n")
print("Reshaped Vector X:")
x_reshape = x.reshape(3,1)
print(x_reshape)

print(f"Reshaped X: Shape {x_reshape.shape} and Dimension {x_reshape.ndim}")



Vector X: Shape (3,) and Dimension 1
Vector Y: Shape (3,) and Dimension 1


Reshaped Vector X:
[[ 2]
 [-1]
 [-8]]
Reshaped X: Shape (3, 1) and Dimension 2


How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

*Broadcasting allows to perform operations on arrays with different shapes. In the following examples, subtraction and multiplication will be performed on 3x3 matrix using a scalar value.*

In [117]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

sub_num = 3 #scalar value for subtraction
mul_num = 4 #scalar value for multiplication

print("Original Matrix:")
print(array)

print("\n")
print("Matrix after subtraction:")
result_subtract = array - sub_num
print(result_subtract)

print("\n")
print("Matrix afer multiplication:")
result_multiple = array * mul_num
print(result_multiple)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Matrix after subtraction:
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


Matrix afer multiplication:
[[ 4  8 12]
 [16 20 24]
 [28 32 36]]


__Part B- Linear Equations__

Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.

__Part B.1__

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

In [118]:
coef_matrix1 = np.array([[4,1,-2],[2,-3,2],[1,2,3]]) #The coefficients of the linear equations (LHS)

d_matrix = np.array([10,-4,6]) #Output of linear equations (RHS)

determinant = np.linalg.det(coef_matrix1)
print("Determinant of the array:", int(determinant))

print("\n")
if determinant != 0 :
    solution = np.linalg.solve(coef_matrix1,d_matrix) #calculate solution of the system
    print("Non-Singular System.Solution of the system:",solution)

else:
    print("Singular System.System can not be solved using numpy functions.")



Determinant of the array: -70


Non-Singular System.Solution of the system: [ 1.8  2.4 -0.2]


__Part B.2__

1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [119]:
coef_matrix2 = np.array([[2,-1,3,4],[4,-2,6,8],[3,1,-2,2],[1,3,-4,1]]) #The coefficients of the linear equations (LHS)

d_matrix2 = np.array([10,20,3,-1]) #Output of linear equations (RHS)

determinant = np.linalg.det(coef_matrix2)
print("Determinant of the array:", int(determinant))

print("\n")
if determinant != 0 :
    solution = np.linalg.solve(coef_matrix2,d_matrix2)
    print("Non-Singular System.Solution of the system:",solution)

else:
    print("Singular System.System can not be solved using numpy functions.")

Determinant of the array: 0


Singular System.System can not be solved using numpy functions.
