In [190]:
import numpy as np
np.__version__

'1.25.2'

In [191]:
# 1. Create an array that starts from the integer 1, ends at 20, incremented by 3.
arr = np.arange(start=1, stop=21, step=3)
print(arr)

[ 1  4  7 10 13 16 19]


In [192]:
# 2. Create a new array of shape 3 with random numbers between 0 and 1.
randomArr = np.random.random(3)
print(randomArr)

[0.81808118 0.94376178 0.55940974]


In [200]:
# 3. Create a 2 D array `[[10,20,45], [30,12,16], [42,17,56]]` and perform the following operations: 
twoDimArr = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# 3.1 Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.
firstTwoRows = twoDimArr[0:2]
lastTwoRows = twoDimArr[1:3]

print("First Two Rows:", "\n", firstTwoRows)
print("Last Two Rows:", "\n", lastTwoRows)

First Two Rows: 
 [[10 20 45]
 [30 12 16]]
Last Two Rows: 
 [[30 12 16]
 [42 17 56]]


In [231]:
# 4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
arr1 = np.array([[7, 2], [9, 4]])
arr2 = np.array([[5, 6], [18, 8]])

print("First 2x2 array:", "\n", arr1)
print("Second 2x2 array:", "\n", arr2)

# Stack elements vertically & horizontally
print("Stacked vertically:", "\n", np.vstack((arr1, arr2)))
print("Stacked horizontally:", "\n", np.hstack((arr1, arr2)))

# Split the arrays into smaller arrays
print("Splited array 1:", "\n", np.split(arr1, 2))
print("Splited array 2:", "\n", np.split(arr2, 2))

First 2x2 array: 
 [[7 2]
 [9 4]]
Second 2x2 array: 
 [[ 5  6]
 [18  8]]
Stacked vertically: 
 [[ 7  2]
 [ 9  4]
 [ 5  6]
 [18  8]]
Stacked horizontally: 
 [[ 7  2  5  6]
 [ 9  4 18  8]]
Splited array 1: 
 [array([[7, 2]]), array([[9, 4]])]
Splited array 2: 
 [array([[5, 6]]), array([[18,  8]])]


In [272]:
# 5. Create two matrices `X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),` 
	# 5.1 Is it possible to multiply these matrices? 
	# 5.2 Demonstrate the case when it is not possible to.

x= np.array(([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) )
y= np.array(([[4, 2], [6, 2], [4, 2]]))

print("3x3 matrix", x.shape)
print("3x2 matrix", y.shape)

if x.shape[1] == y.shape[0]:
    print(np.dot(x, y))

3x3 matrix (3, 3)
3x3 matrix (3, 2)
[[70 28]
 [70 30]
 [60 26]]


#### When the number of the elements within an array is not equal in the two matrices, it is not possible to multiply them, in this case, we can observe it by looking at the second position of the shape function

In [318]:
# 6. Create two arrays, `x = ([2, -1, -8]) y = ([3, 1, -2]),`
#   - Find the Shape, Number of dimensions of vector x.
#   - Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])
shapeX = x.shape
ndimX = x.ndim
print("Shape vector x:","\n",shapeX)
print("Dimensions vector x:","\n",ndimX)
 
reshapedX = x.reshape(3, 1)
reshapedY = y.reshape(3, 1)

print("Vector x reshaped:","\n",reshapedX.ndim)
print("Vector y reshaped:","\n",reshapedY.ndim)

Shape vector x: 
 (3,)
Dimensions vector x: 
 1
Vector x reshaped: 
 2
Vector y reshaped: 
 2


In [319]:
# 7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.
 
threeDimMatrix = np.array([[1, 9, 9],
                   [7, 1, 9],
                   [0, 9, 9]])

subtraction = threeDimMatrix - 1
multiplication = threeDimMatrix * 7
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

Subtraction: [[ 0  8  8]
 [ 6  0  8]
 [-1  8  8]]
Multiplication: [[ 7 63 63]
 [49  7 63]
 [ 0 63 63]]


#### The broadcasting works when it's necessary to make an operation that affects all the values of the matrix, in this case, each operation will take effect on each value and then will generate another matrix with the new values

### To determine the singularity of a system of linear equations, it's important to check the conditions beforehand. 

#### 1. A matrix is singular if its determinant is equal to zero.  

#### 2. If the determinant is zero, the system could have no solutions or infinite solutions.

#### It's possible to solve them by using numpy functions, there is a function in numpy that helps to find the determinant value and the other to solve them np.linalg.det(), np.linalg.solve()

In [327]:
b1 = np.array([[4, 1, -2],
              [2, -3, 2],
              [1, 2, 3]])

values = np.array([10, -4, 6])

determinantB1 = np.linalg.det(b1)
print("Determinant of B1:", determinantB1)

solutionB1 = np.linalg.solve(b1, values)
print("Solution of B1:", solutionB1)


Determinant of B1: -70.00000000000003
Solution of B1: [ 1.8  2.4 -0.2]


In [333]:
b2 = np.array([[2, -1, 3, 4],
              [4, -2, 6, 8],
              [3, 1, -2, 2],
              [1, 3, -4, 1]])

values = np.array([10, 20, 3, -1])

detB2 = np.linalg.det(b2)
print("Determinant of B2:", detB2)

# solutionB2 = np.linalg.solve(b2, values)
# print("Solution of B2:", solutionB2)

# It's not possible to solve it by numpy functions when the determinant of the matrix is 0 (singular)

Determinant of B2: 0.0
