In [3]:
# Array 1-20 
import numpy as np
arr1=np.arange(start=1, stop=20, step=3)
print(arr1)

[ 1  4  7 10 13 16 19]


In [4]:
# Shape 3 array with values between 0 and 1
arr3D=np.random.rand(3,3)
print(arr3D)

[[0.20262463 0.22422234 0.16794877]
 [0.68917481 0.30348969 0.81511164]
 [0.08571996 0.75843277 0.87885409]]


In [5]:
# slicing last and frist 2 rows of a 2D array
list=[[10,20,45],[30,12,16],[42,17,56]]
arr2D=np.array(list)
print(arr2D)

print("\n", arr2D[:2:])
print("\n", arr2D[-2:])

[[10 20 45]
 [30 12 16]
 [42 17 56]]

 [[10 20 45]
 [30 12 16]]

 [[30 12 16]
 [42 17 56]]


In [9]:
#Vertical and Horizontal Stack
a2D=np.array([[1,2,3],[4,5,6]])
a3D=np.array([[10,20,30],[40,50,60]])
print("\n", a2D, "\n", a3D)

vstackedarr=np.vstack((a2D, a3D))
print("\n", vstackedarr)

hstackedarr=np.hstack((a2D, a3D))
print("\n", hstackedarr)


 [[1 2 3]
 [4 5 6]] 
 [[10 20 30]
 [40 50 60]]

 [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]

 [[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [13]:
#Multiplication
n1=np.array([[5,7,2],[4,5,6],[7,4,2]])
n2=np.array([[4,2],[6,2],[4,2]])
print("\n", n1, "\n\n", n2)

product=np.dot(n1,n2)
print("\n The product is : \n", product)

#If n1=([[5,7,2],[4,5,6]]) and n2=([[4,2,6],[2,4,2]]) then the multplication is not possible


 [[5 7 2]
 [4 5 6]
 [7 4 2]] 

 [[4 2]
 [6 2]
 [4 2]]

 The product is : 
 [[70 28]
 [70 30]
 [60 26]]


In [16]:
# Reshaping and finding no. of dimensions
x1=np.array([2,-1,-8])
x2=np.array([3,1,-2])
#finding the shape and no. of dimensions of x1
print("\n", x1.shape, "\n", x1.ndim)

#reshaping both x1,x2 and finding the no. of dimensions of x2
rx1=x1.reshape(3,1)
rx2=x2.reshape(3,1)

print("\n Reshaped : \n", rx1, "\n\n", rx2)
print("\n", rx2.ndim)




 (3,) 
 1

 Reshaped : 
 [[ 2]
 [-1]
 [-8]] 

 [[ 3]
 [ 1]
 [-2]]

 2


In [19]:
#Broadcasting
#It is used for performing operations on different arrays of various shapes
array3D=np.array([[2,4,6],[8,10,12],[14,16,18]])
print("\n", array3D)

sub3D=array3D - 1
mul3D=array3D * 2

print("\n The difference array is : \n", sub3D)
print("\n The product array is : \n", mul3D)


 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

 The difference array is : 
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]

 The product array is : 
 [[ 4  8 12]
 [16 20 24]
 [28 32 36]]
