Bhavesh Thadhani
Lab-1
PartB Link - https://barneyyyyyy.github.io/Fall2023/8897786/Lab1PartB.html


Part-A

1)Created an array which starts at 1, ends at 20 and incremented by 3.

In [150]:
import numpy as np

arr = np.arange(1, 21, 3)
print(arr)


[ 1  4  7 10 13 16 19]


2)Created a new array of shape 3 with random numbers between 0 and 1.

In [151]:
random_arr = np.random.rand(3)
print(random_arr)


[0.09563438 0.44866443 0.86273627]


3)create a 2 D array [[11,15,13], [21,26,29], [14,25,26]] and perform the following operations:
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

Choosed dfferent numbers

In [152]:

import numpy as np

array_2D = np.array([[11, 15, 13], 
                     [21, 26, 29], 
                     [14, 25, 26]])

print("Original 2D Array:\n", array_2D)



Original 2D Array:
 [[11 15 13]
 [21 26 29]
 [14 25 26]]


3.1)Slicing with Negative Indexing

In [153]:
first_two_rows = array_2D[:-1, :]

print("First two rows:\n", first_two_rows)


last_two_rows = array_2D[-2:, :]

print("Last two rows:\n", last_two_rows)



First two rows:
 [[11 15 13]
 [21 26 29]]
Last two rows:
 [[21 26 29]
 [14 25 26]]


3.1)Slicing by omitting the Start or Stop Index

In [154]:
first_two_rows = array_2D[:2, :]

print("First two rows:\n", first_two_rows)



last_two_rows = array_2D[1:, :]

print("Last two rows:\n", last_two_rows)


First two rows:
 [[11 15 13]
 [21 26 29]]
Last two rows:
 [[21 26 29]
 [14 25 26]]


3.1)Sliciing by using Range Function with np.arange

In [155]:
first_two_rows = array_2D[np.arange(2), :]

print("First two rows:\n", first_two_rows)

last_two_rows = array_2D[np.arange(1, 3), :]

print("Last two rows:\n", last_two_rows)


First two rows:
 [[11 15 13]
 [21 26 29]]
Last two rows:
 [[21 26 29]
 [14 25 26]]


4)create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [156]:

import numpy as np

array1 = np.array([[0, 1], 
                   [2, 3]])

array2 = np.array([[4, 5], 
                   [6, 7]])

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)


Array 1:
 [[0 1]
 [2 3]]

Array 2:
 [[4 5]
 [6 7]]


4.1)Vertically stacking the arrays

In [157]:
vstacked = np.vstack((array1, array2))
print("\nVertically Stacked:\n", vstacked)



Vertically Stacked:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


4.2)Horizontally stacking the arrays

In [158]:
hstacked = np.hstack((array1, array2))
print("\nHorizontally Stacked:\n", hstacked)



Horizontally Stacked:
 [[0 1 4 5]
 [2 3 6 7]]


4.3)Splitting the arrays vertically

In [159]:
split_arrays_vertical = np.hsplit(hstacked, 2)
print("\nVertically Split Arrays:\n")
for arr in split_arrays_vertical:
    print(arr)
    print()



Vertically Split Arrays:

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]



4.4)Splitting the arrays Horizontally

In [160]:
split_arrays_horizontal = np.vsplit(vstacked, 2)
print("\nHorizontally Split Arrays:\n")
for arr in split_arrays_horizontal:
    print(arr)
    print()



Horizontally Split Arrays:

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]



5)Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
Is it possible to multiply these matrices?
Demonstrate the case when it is not possible to.

In [161]:
import numpy as np

X = np.array([[5, 7, 2], 
              [4, 5, 6], 
              [7, 4, 2]])

Y = np.array([[4, 2], 
              [6, 2], 
              [4, 2]])

print("Matrix X:\n", X)
print("\nMatrix Y:\n", Y)


Matrix X:
 [[5 7 2]
 [4 5 6]
 [7 4 2]]

Matrix Y:
 [[4 2]
 [6 2]
 [4 2]]


5.1)Multipying the matrices as the number of rows for both matrix are same so we can multiply by dot product

In [162]:
result = np.dot(X, Y)
print("\nResultant Matrix:\n", result)



Resultant Matrix:
 [[70 28]
 [70 30]
 [60 26]]


5.2)For the case of multiplication failing we should have matrices with different number of rows as A has (3,2) and B has (2,3)
For eg

In [163]:
A = np.array([[7, 1], 
              [8, 1], 
              [9, 1]])

B = np.array([[7, 1, 8], 
              [8, 1, 9]])

print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)



Matrix A:
 [[7 1]
 [8 1]
 [9 1]]

Matrix B:
 [[7 1 8]
 [8 1 9]]


6)Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
Find the Shape, Number of dimensions of vector x.
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [164]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Array x:", x)
print("Array y:", y)


Array x: [ 2 -1 -8]
Array y: [ 3  1 -2]


6.1)Shape, number of dimensions of vector x.

In [165]:
print(f"Shape of x: {x.shape}")
print(f"Number of dimensions of x: {x.ndim}")

Shape of x: (3,)
Number of dimensions of x: 1


6.2)Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [166]:
x_reshaped = x.reshape(3,1)
print("\nReshaped x:\n", x_reshaped)

print("Shape of reshaped x:", x_reshaped.shape)
print("Number of dimensions of reshaped x:", x_reshaped.ndim)



Reshaped x:
 [[ 2]
 [-1]
 [-8]]
Shape of reshaped x: (3, 1)
Number of dimensions of reshaped x: 2


6.2)Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [167]:
y_reshaped = y.reshape(3,1)
print("\nReshaped y:\n", y_reshaped)

print("Shape of reshaped y:", y_reshaped.shape)
print("Number of dimensions of reshaped y:", y_reshaped.ndim)



Reshaped y:
 [[ 3]
 [ 1]
 [-2]]
Shape of reshaped y: (3, 1)
Number of dimensions of reshaped y: 2


7)Methods of broadcasting

In [168]:
import numpy as np

# Creating a 3x3 matrix
matrix = np.array([[1, 3, 1], [1, 1, 9], [9, 9, 0]])

# Creating a 1x3 array
array = np.array([1, 0, 1])

print("Original matrix:\n", matrix)
print("\nArray:", array)

# Broadcasting with subtraction
subtracted_result = matrix - array
print("\nSubtraction Result (Broadcasted):\n", subtracted_result)

# Broadcasting with multiplication
multiplied_result = matrix * array
print("\nMultiplication Result (Broadcasted):\n", multiplied_result)


Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array: [1 0 1]

Subtraction Result (Broadcasted):
 [[0 2 2]
 [3 5 5]
 [6 8 8]]

Multiplication Result (Broadcasted):
 [[1 0 3]
 [4 0 6]
 [7 0 9]]
