# __Velon Murugathas__ LAB 1 Assignment

## _Part A_

### 1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [54]:
import numpy as np                  # Importing numpy library for computing

array = np.arange(1, 20, 3)         # To create a regularly spaced array of values within a specified range

print(array)

[ 1  4  7 10 13 16 19]


### 2. Creating an Array of shape 3 with random numbers between 0 and 1.

In [55]:
random_array = np.random.rand(3)    #   To generate random array of length 3 

print(random_array)

[0.56921043 0.3620946  0.35177012]


### 3. Creating a 2-D array and slicing the first and last rows

In [56]:
array_2d = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

first_two_rows = array_2d[:2, :]
last_two_rows = array_2d[1:, :]

print("Initial 2D Array:")
print(array_2d)

print("\nFirst Two Rows:")
print(first_two_rows)

print("\nLast Two Rows:")
print(last_two_rows)

Initial 2D Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

First Two Rows:
[[10 20 45]
 [30 12 16]]

Last Two Rows:
[[30 12 16]
 [42 17 56]]


### 4. Creating two 2x2 arrays and then stack the elements vertically, horizontally, and split the arrays into smaller arrays

In [57]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

vertical_stack = np.vstack((array1, array2))            # To vertically stack arrays
horizontal_stack = np.hstack((array1, array2))          # To horizontally stack arrays

split_vertical = np.vsplit(vertical_stack, 2)           # For splitting an array vertically into multiple sub-arrays.
split_horizontal = np.hsplit(horizontal_stack, 2)       # For splitting an array horizontally into multiple sub-arrays.

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

print("\nVertically Stacked:")
print(vertical_stack)

print("\nHorizontally Stacked:")
print(horizontal_stack)

print("\nSplit Vertically:")
for arr in split_vertical:
    print(arr)

print("\nSplit Horizontally:")
for arr in split_horizontal:
    print(arr)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Vertically Stacked:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally Stacked:
[[1 2 5 6]
 [3 4 7 8]]

Split Vertically:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

Split Horizontally:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


#### 5. Reasons why the multiplication of matrices is possible
* Yes, it is possible to multiply both matrices.
* The size of matrix X is 3x3 and Y is 3x2.
* Since the number colums of the first matrix (X) and the number of rows of the second matrix (Y) are equal the multiplication is possible.
* The result matrix would be a 3x2 matrix.

In [58]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

result = np.dot(X, Y)                       # Compute the dot product of two arrays (matrices) or inner product of vectors.

print("X:")
print(X)

print("\nY:")
print(Y)

print("\nResult of matrix multiplication (X * Y):")
print(result)

X:
[[5 7 2]
 [4 5 6]
 [7 4 2]]

Y:
[[4 2]
 [6 2]
 [4 2]]

Result of matrix multiplication (X * Y):
[[70 28]
 [70 30]
 [60 26]]


#### Scenario when matrix multiplication is not possible

<p>If the number colums of the first matrix and the number of rows of the second matrix are different then the matrix multiplication is not possible. Consider the scenario below,</p>

<p>A = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])</p>
<p>B = np.array([[4, 2, 3], [6, 2, 1]])</p>
<p>result = np.dot(A, B)</p>

* When this code is executed it will throw this error "ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)"

#### 6. Finding shapes and Reshaping the arrays

In [59]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

x_shape = x.shape                   # To get the dimensions of the array
x_dimensions = x.ndim

x_reshaped = x.reshape(3, 1)        # Reshaping the array x into a 3x1 matrix

y_reshaped = y.reshape(3, 1)
y_dimensions_after_reshape = y_reshaped.ndim

print("Vector x:")
print(x)
print("Shape of x:", x_shape)
print("Number of dimensions of x:", x_dimensions)

print("\nReshaped x (matrix of size (3,1)):")
print(x_reshaped)

print("\nReshaped y (matrix of size (3,1)):")
print(y_reshaped)
print("Number of dimensions of y after reshaping:", y_dimensions_after_reshape)

Vector x:
[ 2 -1 -8]
Shape of x: (3,)
Number of dimensions of x: 1

Reshaped x (matrix of size (3,1)):
[[ 2]
 [-1]
 [-8]]

Reshaped y (matrix of size (3,1)):
[[ 3]
 [ 1]
 [-2]]
Number of dimensions of y after reshaping: 2


#### 7. Broadcasting

<p>Broadcasting in NumPy allows arrays with different shapes to be combined and used in operations together. It's like a set of rules that NumPy follows to make arrays with mismatched shapes. compatible for element-wise operations.</p>

* In the code below a 3x3 matrix has been created and named as matrix.
* Then subtract 2 from the entire matrix and multiply the entire matrix by 3 using broadcasting.
* Broadcasting automatically applies the operation to each element of the matrix, in this case, subtracting 2 and multiplying by 3 element-wise.
* Then the matrix is shown after subtracting 2, and the matrix after multiplication by 3, all achieved through broadcasting.

These 2 examples below shows NumPy broadcasting, which allows efficient element-wise operations between arrays and scalars.

In [60]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

result_subtract = matrix - 2            # Each element in result_subtract is obtained by subtracting 2 from the corresponding element in the matrix

result_multiply = matrix * 3            # Each element in result_subtract is obtained by multiplying 3 from the corresponding element in the matrix

print("Original Matrix:")
print(matrix)

print("\nSubtract 2 using Broadcasting:")
print(result_subtract)

print("\nMultiply by 3 using Broadcasting:")
print(result_multiply)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtract 2 using Broadcasting:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Multiply by 3 using Broadcasting:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


## _Part B_

### Part B.1

<p>4x +  y - 2z = 10</p>
<p>2x - 3y + 2z = -4</p>
<p> x + 2y + 3z =  6</p>



A = |  4   1  -2 |
    |  2  -3   2 |
    |  1   2   3 |

x = | x |
    | y |
    | z |

B = | 10 |
    | -4 |
    |  6 |

#### Justification

<p>If the determinant of the coefficient matrix is not zero, there is a unique solution to the system of equations; but if the determinant is zero, the system is singular, and solutions may either not exist or be infinite.</p>

In [61]:
A = np.array([[4, 1, -2],
              [2, -3, 2],
              [1, 2, 3]])

det_A = np.linalg.det(A)

print("Determinant of A is " , det_A)

if det_A != 0:
    print("The system is non-singular, and a unique solution exists.")
    solution = np.linalg.solve(A, np.array([10, -4, 6]))
    print("Solution (x, y, z):", solution)
else:
    print("The system is singular")


Determinant of A is  -70.00000000000003
The system is non-singular, and a unique solution exists.
Solution (x, y, z): [ 1.8  2.4 -0.2]


### Part B.2

2x - y + 3z + 4w = 10
4x - 2y + 6z + 8w = 20
3x + y - 2z + 2w = 3
  x + 3y - 4z +   w = -1


A = |  2  -1   3   4 |
    |  4  -2   6   8 |
    |  3   1  -2   2 |
    |  1   3  -4   1 |

x = | x |
    | y |
    | z |
    | w |

B = | 10 |
    | 20 |
    |  3 |
    | -1 |

#### Justification

<p>If the determinant of the coefficient matrix is not zero, there is a unique solution to the system of equations; but if the determinant is zero, the system is singular, and solutions may either not exist or be infinite.</p>

In [62]:
A = np.array([[2, -1, 3, 4],
              [4, -2, 6, 8],
              [3, 1, -2, 2],
              [1, 3, -4, 1]])

det_A = np.linalg.det(A)

print("Determinant of A is " , det_A)

if det_A != 0:
    print("The system is non-singular, and a unique solution exists.")
    solution = np.linalg.solve(A, np.array([10, 20, 3, -1]))
    print("Solution (x, y, z, w):", solution)
else:
    print("The system is singular")

Determinant of A is  0.0
The system is singular
