# Part A- Create a Notebook to demonstrate NumPy Operations.

## Question 1: Create an array that starts from the integer 1, ends at 20, incremented by 3.

### Solution 1

In [8]:
import numpy as np #importing numpy library

array_inc3=np.arange(1,20,3) #creating a array which starts with 1 and increases with a step size of 3 till 20
print(array_inc3) #printing array

[ 1  4  7 10 13 16 19]


## Question 2: Create a new array of shape 3 with random numbers between 0 and 1.

### Solution 2

In [19]:
import numpy as np #importing numpy library
#from numpy import random # 
#array_shp3=np.arange()
array_3=np.random.rand(3) #generating random 3 numbers between 0 and 1
print(array_3) # printing an array of shape 3 


[0.81007433 0.99012908 0.96815985]


In [23]:
import numpy as np #importing numpy library
from numpy import random
#array_shp3=np.arange()
array_3=np.random.rand(1,size(1,3)) #generating random 3 numbers between 0 and 1
print(array_3)

NameError: name 'size' is not defined

## Question 3 : Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

### Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.


### Solution 3 :

In [31]:
import numpy as np
array_2D=np.array([[10,20,45],
                  [30,12,16],
                  [42,17,56]])  #creating given 2D array
print(array_2D)

array_first2=array_2D[:2]  #slicing first 2 rows of given 2D array
print(array_first2) #printing first 2 rows of given 2D array

array_last2=array_2D[-2:] #slicing last 2 rows of given 2D array
print(array_last2) #printing last 2 rows of given 2D array

[[10 20 45]
 [30 12 16]
 [42 17 56]]
[[10 20 45]
 [30 12 16]]
[[30 12 16]
 [42 17 56]]


## Question 4 : Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

### Solution 4 :

In [43]:
import numpy as np #importing numpy library

array1=np.random.randint(100,size=(2,2)) #creating a 2x2 array
print(array1) #printing first 2x2 array

array2=np.random.randint(100,size=(2,2))  #creating second 2x2 array
print(array2) #printing second 2x2 array

array_ver=np.vstack((array1,array2)) #stacking vertically both arrays
print(array_ver) #printing vertically stacked arrays


array_hor=np.hstack((array1,array2)) #stacking horizontally both arrays
print(array_hor) #printing horizontally stacked arrays

array_splitv=np.vsplit(array_hor,1) #splitting array vertically
print(array_splitv) #printing vertically split array






[[89 90]
 [71 10]]
[[28 59]
 [53 40]]
[[89 90]
 [71 10]
 [28 59]
 [53 40]]
[[89 90 28 59]
 [71 10 53 40]]
[array([[89, 90, 28, 59],
       [71, 10, 53, 40]])]


## Question 5 : Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]])
### Is it possible to multiply these matrices?
### Demonstrate the case when it is not possible to.

### Solution 5 :

In [56]:
import numpy as np
mat1=np.array([[5,7,2],
                  [4,5,6],
                  [7,4,2]])  #creating given matrix 1
print(mat1)

mat2=np.array([[4,2],
                [6,2],
                [4,2]])  #creating given matrix 2
print(mat2)


matprod=np.dot(mat1,mat2) #product of two matrices
print(matprod) #printing the new matrix

mat2_ex=mat2[:2] #slicing matrix 2 for top 2 rows
print(mat2_ex) #printing sliced matrix 2


[[5 7 2]
 [4 5 6]
 [7 4 2]]
[[4 2]
 [6 2]
 [4 2]]
[[70 28]
 [70 30]
 [60 26]]
[[4 2]
 [6 2]]


### Demonstration of when product of matrices is not possible

In [58]:
import numpy as np
mat1=np.array([[5,7,2],
                  [4,5,6],
                  [7,4,2]])  #creating given matrix 1
print(mat1)

mat2=np.array([[4,2],
                [6,2],
                [4,2]])  #creating given matrix 2
print(mat2)


matprod=np.dot(mat1,mat2) #product of two matrices
print(matprod) #printing the new matrix

mat2_ex=mat2[:2] #slicing matrix 2 for top 2 rows
print(mat2_ex) #printing sliced matrix 2

matprod_new=np.dot(mat1,mat2_ex) #product of two matrix which has different dimensions (basically columns of first matrix should be equal to row of second matrix for the product to happen)
print(matprod_new) #this will not work as number of columns in first matrx is different than number of rows in second matrix

[[5 7 2]
 [4 5 6]
 [7 4 2]]
[[4 2]
 [6 2]
 [4 2]]
[[70 28]
 [70 30]
 [60 26]]
[[4 2]
 [6 2]]


ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

## Question 6: Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
### Find the Shape, Number of dimensions of vector x.
### Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).


In [64]:
import numpy as np
x=np.array([2,-1,-8]) # creating first array

y=np.array([3,1,-2]) # creating second array

shpx=x.shape
print(shpx)  # shape of vector x

dimx=x.ndim
print(dimx) # dimensions of vector x

rex=x.reshape(3,1)
print(rex)  # reshaping vector x to size (3,1)


rexdim=rex.ndim
print(rexdim) # dimensions of new reshaped vector x

(3,)
1
[[ 2]
 [-1]
 [-8]]
2


## Question 7 : How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

## Solution 7


## Broadcasting of matrices allows us to perform multiple operations like addition, multiplication , subtraction
## throughout an array without looping over each element. 
## The name broadcasting comes from how NumPy handles these operations, it essentially broadcasts a small  array in the larger array to turn them into compatible shapes. 

### Example for multiplication and subtraction

In [68]:
firstArray = np.random.randint(100,size=(3,3))
secondArray = np.random.randint(100,size=(3,3))

print(firstArray) #printing first array
print(secondArray) #printing second array

differenceArray = firstArray - secondArray #subtraction of 2 arrays
productArray = firstArray * secondArray #product of 2 arrays

print(differenceArray) #print difference array
print(productArray) #print product array



[[33  8 29]
 [44 35 35]
 [55  2 63]]
[[78 24 11]
 [73 52  6]
 [77 65 17]]
[[-45 -16  18]
 [-29 -17  29]
 [-22 -63  46]]
[[2574  192  319]
 [3212 1820  210]
 [4235  130 1071]]
