## <center>Dev Bharatbhai Patel(8938546)</center>
### <center>Lab-1 Basic Numpy Operations</center>



**Part A- Create a Notebook to demonstrate NumPy Operations.**

<font color='indigo'>1. Create an array that starts from the integer 1, ends at 20, incremented by 3.</font>

In [1]:
## Importing numpy package
import numpy as np

## Creating an array using np.arange() function.
array = np.arange(1, 20, 3)

## Printing the result.
print(array)

[ 1  4  7 10 13 16 19]


<font color='indigo'>2. Create a new array of shape 3 with random numbers between 0 and 1.</font>

In [2]:
## Creating an array by using the np.random.rand() function to generate random numbers between 0 and 1 for array of shape-3.
random = np.random.rand(3)

## Printing the result.
print(random)

[0.13748756 0.07965484 0.96175805]


<font color='indigo'>3. Create a 2 D array `[[10, 20, 45], [30, 12, 16], [42, 17, 56]]` and perform the following operations:-</font>

-  <font color='indigo'>Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.</font>

In [3]:
## Creating a 2D array
array2D = np.array([[10, 20, 45], [30, 12, 16],[42, 17, 56]])

## Slicing the 2D array to get First 2 rows.
print(array2D[0:2])

## Slicing the 2D array to get the last 2 rows.
print("\n",array2D[1:3])

[[10 20 45]
 [30 12 16]]

 [[30 12 16]
 [42 17 56]]


<font color='indigo'>4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.</font>

In [4]:
## Creating two 2x2 arrays.
array1 = np.array([[1, 2],[3, 4]])
array2 = np.array([[5, 6],[7, 8]])

## Stacking the elements vertically using vstack() function.
vertical_stack = np.vstack((array1, array2))

## Stacking the elements horizontally using hstack() function.
horizontal_stack = np.hstack((array1, array2))

## Splitting the arrays into smaller arrays using split() function.
split_array1 = np.split(array1,2)
split_array2 = np.split(array2,2)

## Printing the Results.
print(vertical_stack)
print("\n",horizontal_stack)
print("\n",split_array1)
print("\n",split_array2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

 [[1 2 5 6]
 [3 4 7 8]]

 [array([[1, 2]]), array([[3, 4]])]

 [array([[5, 6]]), array([[7, 8]])]


<font color='indigo'>5. Create two matrices `X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]])`</font>

- <font color='indigo'>Is it possible to multiply these matrices? </font>

In [5]:
## Creating 2 matrices.
X = np.array([[5, 7, 2], [4, 5, 6],[7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]]) 

## Multiplying the matrices by using the np.dot() function.
print(np.dot(X,Y))

[[70 28]
 [70 30]
 [60 26]]


- <font color='indigo'>Demonstrate the case when it is not possible to. </font>

In [6]:
## Demonstrating when multiplication is not possible.
print(np.dot(Y,X))

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

   - *When we try to multiply these matrices it will gives us an error.*
   - *Well, in order to multiply two matrices, the number of columns in the first matrix must be equal to the number of rows in the second matrix. In the given example, the number of columns in the Y matrix is not equal to the number of rows in the X matrix. Therefore, multiplication is not possible.*
    

<font color='indigo'>6. Create two arrays, `x = ([2, -1, -8]) y = ([3, 1, -2])` </font>

 - <font color='indigo'>Find the Shape, Number of dimensions of vector x.</font>

In [ ]:
## Creating 2 arrays.
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

## Finding the shape of vector x using shape() function.
print(x.shape)

## Finding the dimensions of vector x using ndim() function.
print("\n",x.ndim)

(3,)

 1


- <font color='indigo'>Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).</font>

In [ ]:
## Reshaping the matrix of vector x using the reshape() function.
print(x.reshape(3, 1))

## Reshaping the matrix of vector y using the same function.
reshape_y = y.reshape(3, 1)

## Determining the number of dimensions.
print("\n",reshape_y.ndim)

[[ 2]
 [-1]
 [-8]]

 2


<font color='indigo'>7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.</font>

-  *In order to enable element-wise operations, broadcasting automatically expands the smaller array to take the shape of the larger array.*

In [ ]:
## Creating a 3 x 3 matrix.
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

  - <font color='indigo'>Subtraction</font>

In [ ]:
## Subracting by single value.
print(np.subtract(A, 5))

## Subracting by Rows.
print("\n", np.subtract(A, [[-4], [7], [-1]]))

## Subracting by columns.
print("\n",np.subtract(A,[-5, -2, 3]))

[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]

 [[ 5  6  7]
 [-3 -2 -1]
 [ 8  9 10]]

 [[ 6  4  0]
 [ 9  7  3]
 [12 10  6]]


  - <font color='indigo'>Multiplication</font>

In [ ]:
## Multiplying by single value
print(np.multiply(A, 8))

## Multiplying by Rows.
print("\n", np.multiply(A, [[2], [6], [1]]))

## Multiplying by columns.
print("\n",np.multiply(A,[-9, 3, -5]))

[[ 8 16 24]
 [32 40 48]
 [56 64 72]]

 [[ 2  4  6]
 [24 30 36]
 [ 7  8  9]]

 [[ -9   6 -15]
 [-36  15 -30]
 [-63  24 -45]]


**Part B- Linear Equations**

- <font color='indigo'>Part B.1</font>
    -  <font color='indigo'>4x + y - 2z = 10</font>
    -  <font color='indigo'>2x - 3y + 2z = -4</font>
    -  <font color='indigo'>x + 2y + 3z = 6</font>


In [ ]:
## Converting the linear equations to the matrix.
a = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])
b = np.array([10, -4, 6])

## Calculating the determinant of the matrix a by using the np.linalg.det() functions.
print(np.linalg.det(a))

-70.00000000000003


*As we can see in the above line code the determinant of the matrix 'a' is not zero and in addition to that it is non-singular. Thus, the linear equation is solved.*

- <font color='indigo'>Part B.2</font>
    - <font color='indigo'>2x - y + 3z + 4w = 10</font>
    - <font color='indigo'>4x - 2y + 6z + 8w = 20</font>
    - <font color='indigo'>3x + y - 2z + 2w = 3</font>
    - <font color='indigo'>x + 3y - 4z + w = -1</font>

In [ ]:
## Running the same process as above.
d = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])
e = np.array([10, 20, 3, -1])

print(np.linalg.det(d))

0.0


*As we can see in the above code that we got the result zero because the matrix is singular. So, the equal is unsolvable.*