# <span style="color:pink"><center>  Lab 1 – Basic NumPy Operations<center>
---
Student Name: **Zeel Samir Shah** <br>
Student ID: **8947091**

## Part A- Create a Notebook to demonstrate NumPy Operations.

<span style="color:pink">1] Create an array that starts from the integer 1, ends at 20, incremented by 3.</span>

In [7]:
import numpy as np

array = np.arange(1, 20, 3)
print(array)


[ 1  4  7 10 13 16 19]


<span style="color:pink">2] Create a new array of shape 3 with random numbers between 0 and 1.</span>

In [8]:
import numpy as np

array = np.random.rand(3)
print(array)


[0.12481201 0.12800608 0.43553446]


<span style="color:pink">3] Create a 2 D array `[[10,20,45], [30,12,16], [42,17,56]]` and perform the following operations: 
 - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.</span>

In [9]:
import numpy as np

array = np.array([[10,20,45], [30,12,16], [42,17,56]])

first_two_rows = array[:2]
last_two_rows = array[-2:]

print(first_two_rows)
print(last_two_rows)


[[10 20 45]
 [30 12 16]]
[[30 12 16]
 [42 17 56]]


<span style="color:pink">4] Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.</span>

In [27]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print("\nArray1:")
print(array1)
print("\nArray2:")
print(array2)

stacked_array = np.vstack((array1, array2))
print("\nStacked vertically:")
print(stacked_array)

stacked_array = np.hstack((array1, array2))
print("\nStacked horizontally:")
print(stacked_array)

split_arrays = np.split(array1, 2, axis=1)
print("\nSplited Smaller Arrays:")
print(split_arrays)






Array1:
[[1 2]
 [3 4]]

Array2:
[[5 6]
 [7 8]]

Stacked vertically:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Stacked horizontally:
[[1 2 5 6]
 [3 4 7 8]]

Splited Smaller Arrays:
[array([[1],
       [3]]), array([[2],
       [4]])]


<span style="color:pink">5] Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
- Is it possible to multiply these matrices? 
 <br> **Answer**: Yes, it is possible to multiply the two matrices X and Y that you have provided. To multiply two matrices, the number of columns in the first matrix must be equal to the number of rows in the second matrix. In this case, the first matrix X has 3 columns and the second matrix Y has 3 rows. Therefore, the two matrices can be multiplied.
- Demonstrate the case when it is not possible to.
 <br>**Answer:** When we try to multiply Y with X, we can't multiply. Both examples are demonstrated below.</span>

In [29]:
import numpy as np

X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

product = np.dot(X, Y)

print(product)



[[70 28]
 [70 30]
 [60 26]]


<span style="color:pink">6] Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
- Find the Shape, Number of dimensions of vector x.
- Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).</span>

In [30]:
import numpy as np

x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Shape of vector x:", x.shape)
print("Number of dimensions of vector x:", x.ndim)

x_reshaped = x.reshape((3, 1))

y_reshaped = y.reshape((3, 1))
print("Number of dimensions after reshaping y to a matrix of (3,1):", y_reshaped.ndim)


Shape of vector x: (3,)
Number of dimensions of vector x: 1
Number of dimensions after reshaping y to a matrix of (3,1): 2


<span style="color:pink">7] How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.</span>
<br>**Answer :** Broadcasting works by expanding the smaller array to the shape of the larger array. This allows you to perform arithmetic operations on arrays of different shapes without having to explicitly reshape them.

In [33]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A - 5

C = A * 2

print(B)
print(C)


[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


---
## Part B- Linear Equations
Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.
### <span style="color:pink">Part B.1</span>

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

<span style="color:pink">Answer:</span>
==> To determine the singularity of a system of equations, we can use the determinant of the coefficient matrix. If the determinant is zero, then the system of equations is singular. If the determinant is non-zero, then the system of equations has a unique solution.

Let's calculate the determinant and solve the system:

In [34]:
import numpy as np

A = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])
b = np.array([10, -4, 6])

x = np.linalg.solve(A, b)

print(x)


[ 1.8  2.4 -0.2]


### <span style="color:pink">Part B.2</span>
1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [35]:
import numpy as np

A = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])
b = np.array([10, 20, 3, -1])

try:
  x = np.linalg.solve(A, b)
except np.linalg.LinAlgError:
  print("The system of equations is singular.")


The system of equations is singular.
