In [1]:
import numpy as np

Question A.1

In [4]:
arr_1 = np.arange(1, 21, 3)
print(arr_1)

[ 1  4  7 10 13 16 19]


Question A.2

In [5]:
# Task 2
arr_2 = np.random.rand(3)
print(arr_2)

[0.30376297 0.25539001 0.12172039]


Question A.3

In [6]:
# Task 3
arr_3 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
first_two_rows = arr_3[:2]
print("First two rows:", first_two_rows)
last_two_rows = arr_3[1:]
print("Last two rows:", last_two_rows)

First two rows: [[10 20 45]
 [30 12 16]]
Last two rows: [[30 12 16]
 [42 17 56]]


Question A.4

In [7]:
arr_4a = np.array([[1, 2], [3, 4]])
arr_4b = np.array([[5, 6], [7, 8]])

# Vertical stack
vertical_stack = np.vstack((arr_4a, arr_4b))
print("Vertical Stack:", vertical_stack)

# Horizontal stack
horizontal_stack = np.hstack((arr_4a, arr_4b))
print("Horizontal Stack:", horizontal_stack)

# Split into smaller arrays
split_array = np.split(vertical_stack, 2)  # Split into 2 smaller arrays along vertical axis
print("Split Array:", split_array)


Vertical Stack: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack: [[1 2 5 6]
 [3 4 7 8]]
Split Array: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


Question A.5

In [8]:

X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

Matrix Multiplication: [[70 28]
 [70 30]
 [60 26]]


its possible because shape of x is 3x3 and y is 3x2  
the column of x and row of y is same. hence x*y is possible.

In [ ]:

# Matrix multiplication
result = np.dot(X, Y)
print("Matrix Multiplication:", result)

the reverse case is impossible because column of y and row of x is not same

Question A.6

In [9]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Shape and number of dimensions
print("x Shape:", x.shape)
print("x Dimensions:", x.ndim)

# Reshape to (3, 1)
x_reshaped = x.reshape((3, 1))
y_reshaped = y.reshape((3, 1))
print("x Reshaped:", x_reshaped)
print("y Reshaped:", y_reshaped)

# Number of dimensions after reshaping
x_reshaped_dimensions = x_reshaped.ndim
y_reshaped_dimensions = y_reshaped.ndim
print("x Reshaped Dimensions:", x_reshaped_dimensions)
print("y Reshaped Dimensions:", y_reshaped_dimensions)


x Shape: (3,)
x Dimensions: 1
x Reshaped: [[ 2]
 [-1]
 [-8]]
y Reshaped: [[ 3]
 [ 1]
 [-2]]
x Reshaped Dimensions: 2
y Reshaped Dimensions: 2


Question A.7

In [11]:
# Broadcasting example
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([10, 20, 30])

# Subtract vector b from matrix a using broadcasting
result_subtraction = a - b
print("Broadcasting Subtraction:", result_subtraction)

# Multiply matrix by vector using broadcasting
result_multiplication = a * b
print("Broadcasting Multiplication:", result_multiplication)

Broadcasting Subtraction: [[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]
Broadcasting Multiplication: [[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


## Part B

Question B.1

In [17]:
B1 = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])

In [18]:
print(np.linalg.det(B1))

-70.00000000000003


the above matrix is non singular because the determinent is not a zero.  
the system of equation has the solution beacsue its non singular

In [15]:
b = np.array([10, -4, 6])

In [21]:
x, y, z = np.linalg.solve(B1, b)

In [23]:
print('The solution is ')
print('x=', x)
print('y=', y)
print('z=', z)

The solution is 
x= 1.7999999999999998
y= 2.4
z= -0.2


Question B.2

In [19]:
B2 = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])

In [20]:
print(np.linalg.det(B2))

0.0


the above matrix is non singular because the determinent zero.  
the system of equation does not has the solution beacsue its singular.