In [3]:
frarr = [x for x in range(1, 21, 3)]
print(frarr)

[1, 4, 7, 10, 13, 16, 19]


In [4]:
import numpy as np

# Create a random array with shape (3,) and values between 0 and 1
secarr = np.random.rand(3)

print(secarr)

[0.23720759 0.82191038 0.44346817]


In [5]:
import numpy as np

# Create the 2D array
thrdarr = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# Slice to get the first two rows
first_two_rows = thrdarr[:2]

# Slice to get the last two rows
last_two_rows = thrdarr[1:]

# Print the results
print("First two rows:")
print(first_two_rows)

print("\nLast two rows:")
print(last_two_rows)

First two rows:
[[10 20 45]
 [30 12 16]]

Last two rows:
[[30 12 16]
 [42 17 56]]


In [6]:
import numpy as np

# Create two 2x2 arrays
fotharr = np.array([[1, 2], [3, 4]])
fitharr = np.array([[5, 6], [7, 8]])

# Stack them vertically
vertical_stack = np.vstack((fotharr, fitharr))

# Stack them horizontally
horizontal_stack = np.hstack((fotharr, fitharr))
# Split the vertically stacked array into two smaller arrays
split_vertical = np.split(vertical_stack, 2)

# Split the horizontally stacked array into two smaller arrays
split_horizontal = np.split(horizontal_stack, 2, axis=1)

# Print the results
print("Array 1:")
print(fotharr)

print("\nArray 2:")
print(fitharr)

print("\nVertically Stacked:")
print(vertical_stack)
print("\nHorizontally Stacked:")
print(horizontal_stack)
print("\nSplit Vertically:")
print(split_vertical)

print("\nSplit Horizontally:")
print(split_horizontal)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Vertically Stacked:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally Stacked:
[[1 2 5 6]
 [3 4 7 8]]

Split Vertically:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

Split Horizontally:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [7]:
import numpy as np

# Define matrices X and Y
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Try to multiply X and Y
try:
    result = np.dot(X, Y)
except ValueError as e:
    result = str(e)
    print("Matrix X:")
print(X)

print("\nMatrix Y:")
print(Y)

print("\nResult of X * Y:")
print(result)

[[5 7 2]
 [4 5 6]
 [7 4 2]]

Matrix Y:
[[4 2]
 [6 2]
 [4 2]]

Result of X * Y:
[[70 28]
 [70 30]
 [60 26]]


In [8]:
import numpy as np

# Create the arrays
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Find the shape and number of dimensions of vector x
x_shape = x.shape
x_dimensions = x.ndim

# Reshape vector x to a matrix of size (3, 1)
x_reshaped = x.reshape(3, 1)

# Reshape vector y to a matrix of size (3, 1) and determine the number of dimensions
y_reshaped = y.reshape(3, 1)
y_dimensions = y_reshaped.ndim

# Print the results
print("Vector x:")
print("Shape:", x_shape)
print("Number of Dimensions:", x_dimensions)

print("\nReshaped Matrix x:")
print(x_reshaped)

print("\nReshaped Matrix y:")
print(y_reshaped)
print("Number of Dimensions after reshaping y:", y_dimensions)

Vector x:
Shape: (3,)
Number of Dimensions: 1

Reshaped Matrix x:
[[ 2]
 [-1]
 [-8]]

Reshaped Matrix y:
[[ 3]
 [ 1]
 [-2]]
Number of Dimensions after reshaping y: 2


In [9]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Subtract a scalar (5) from the matrix using broadcasting
subtracted_matrix = matrix - 5
# Multiply the matrix by a scalar (2) using broadcasting
multiplied_matrix = matrix * 2

# Print the original matrix and the results of subtraction and multiplication
print("Original Matrix:")
print(matrix)

print("\nSubtracted Matrix (matrix - 5):")
print(subtracted_matrix)

print("\nMultiplied Matrix (matrix * 2):")
print(multiplied_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtracted Matrix (matrix - 5):
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]

Multiplied Matrix (matrix * 2):
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
