# Creating a NumPy Array with a Specified Range and Increment

In [12]:
import numpy as np

myRange = np.arange(1, 21, 3)
print(myRange)

[ 1  4  7 10 13 16 19]


# Creating a NumPy Array with Random Numbers

In [13]:
import numpy as np

randomArray = np.random.rand(3)
print(randomArray)

[0.43140808 0.64582801 0.26077108]


# Creating a 2D Array and Performing Slicing

In [16]:
import numpy as np

# Create a 2D array
myArray = np.array([[13, 24, 35],
                     [39, 4, 56],
                     [41, 8, 33]])

first_two_rows = myArray[:2, :]

last_two_rows = myArray[1:, :]

print("my array")
print(myArray)

print("\nfirst 2 rows")
print(first_two_rows)

print("\nlast 2 rows")
print(last_two_rows)


my array
[[13 24 35]
 [39  4 56]
 [41  8 33]]

first 2 rows
[[13 24 35]
 [39  4 56]]

last 2 rows
[[39  4 56]
 [41  8 33]]


# Creating and Manipulating 2x2 Arrays in NumPy

In [17]:
import numpy as np

firstArray = np.array([[1, 2],
                   [3, 4]])

secondArray = np.array([[5, 6],
                   [7, 8]])

vertical = np.vstack((firstArray, secondArray))
horizontal = np.hstack((firstArray, secondArray))
splitArrays = np.hsplit(horizontal, 2)

print("first array")
print(firstArray)
print("\nsecond array")
print(secondArray)
print("\nvertical")
print(vertical)
print("\nhorizontally")
print(horizontal)
print("\nsplit")
print(splitArrays)


first array
[[1 2]
 [3 4]]

second array
[[5 6]
 [7 8]]

vertical
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

horizontally
[[1 2 5 6]
 [3 4 7 8]]

split
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# Matrix Multiplication and Checking Validity

In [18]:
import numpy as np

X = np.array([[5, 7, 2],
              [4, 5, 6],
              [7, 4, 2]])

Y = np.array([[4, 2],
              [6, 2],
              [4, 2]])

if X.shape[1] == Y.shape[0]:
    result = np.dot(X, Y)
    multiPossible = True
else:
    multiPossible = False

print("multiplication possible?", multiPossible)

if multiPossible:
    print("\nResult:")
    print(result)
else:
    print("\nMatrix multiplication is not possible because the number of columns in X is not equal to the number of rows in Y.")


multiplication possible? True

Result:
[[70 28]
 [70 30]
 [60 26]]


# Working with NumPy Arrays: Shape and Reshaping


In [24]:
import numpy as np

x = np.array([12, -33, 8])
y = np.array([33, -1, 22])

xShape = x.shape
xDimensions = x.ndim

xReshaped = x.reshape((3, 1))

yReshaped = y.reshape((3, 1))

yReshapedDimensions = yReshaped.ndim

print("vector x")
print("shape:", xShape)
print("num of dimensions", xDimensions)

print("\nreshaped x")
print(xReshaped)

print("\nreshaped y")
print(yReshaped)
print("num of dimensions afterreshaping y", yReshapedDimensions)


vector x
shape: (3,)
num of dimensions 1

reshaped x
[[ 12]
 [-33]
 [  8]]

reshaped y
[[33]
 [-1]
 [22]]
num of dimensions afterreshaping y 2


# Broadcasting in NumPy: Subtraction and Multiplication

In [27]:
import numpy as np

matrix = np.array([[33, -2, 13],
                   [4, 52, 60],
                   [19, 4, 21]])

scalarValue = 2
resultSub = matrix - scalarValue
resultMulti = matrix * scalarValue

print("original")
print(matrix)

print("\nsubtraction")
print(resultSub)

print("\nmultiplication")
print(resultMulti)


original
[[33 -2 13]
 [ 4 52 60]
 [19  4 21]]

subtraction
[[31 -4 11]
 [ 2 50 58]
 [17  2 19]]

multiplication
[[ 66  -4  26]
 [  8 104 120]
 [ 38   8  42]]
