Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [1]:
my_array = [i for i in range(1, 21, 3)]
print(my_array)

[1, 4, 7, 10, 13, 16, 19]


A new array of shape 3 with random numbers between 0 and 1. without comment

In [2]:
import numpy as np

random_array = np.random.uniform(0, 1, 3)
print(random_array)

[0.51479709 0.64269278 0.60679456]


Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows. without comments

In [3]:
import numpy as np


array_2d = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])


first_two_rows = array_2d[:2]
last_two_rows = array_2d[1:]
print("First two rows:")
print(first_two_rows)
print("Last two rows:")
print(last_two_rows)


First two rows:
[[10 20 45]
 [30 12 16]]
Last two rows:
[[30 12 16]
 [42 17 56]]


Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays. code without comment

In [4]:
import numpy as np


array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
vertical_stack = np.concatenate((array1, array2), axis=0)
horizontal_stack = np.concatenate((array1, array2), axis=1)
split_horizontal = np.split(horizontal_stack, 2, axis=1)
split_vertical = np.split(vertical_stack, 2, axis=0)

print("Original Arrays:")
print(array1)
print(array2)

print("Stacked Vertically:")
print(vertical_stack)

print("Stacked Horizontally:")
print(horizontal_stack)

print("Split Horizontally:")
for sub_array in split_horizontal:
    print(sub_array)

print("Split Vertically:")
for sub_array in split_vertical:
    print(sub_array)


Original Arrays:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Stacked Vertically:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stacked Horizontally:
[[1 2 5 6]
 [3 4 7 8]]
Split Horizontally:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Split Vertically:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]



Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
Is it possible to multiply these matrices?
Demonstrate the case when it is not possible to. code without comments

In [5]:
import numpy as np

X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

if X.shape[1] == Y.shape[0]:
    result = np.dot(X, Y)
    print("Matrix Multiplication Result:")
    print(result)
else:
    print("Matrix multiplication is not possible due to incompatible dimensions.")


Matrix Multiplication Result:
[[70 28]
 [70 30]
 [60 26]]


Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
Find the Shape, Number of dimensions of vector x.
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).  code without comment

In [6]:
import numpy as np

x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

x_shape = x.shape
x_dimensions = x.ndim

x_reshaped = x.reshape(-1, 1)
y_reshaped = y.reshape(-1, 1)
y_reshaped_dimensions = y_reshaped.ndim

print("Shape of x:", x_shape)
print("Number of dimensions of x:", x_dimensions)

print("Reshaped x:")
print(x_reshaped)

print("Number of dimensions after reshaping y:", y_reshaped_dimensions)


Shape of x: (3,)
Number of dimensions of x: 1
Reshaped x:
[[ 2]
 [-1]
 [-8]]
Number of dimensions after reshaping y: 2


How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix. a code without comment



In [7]:
import numpy as np


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

result_subtraction = matrix - np.array([2, 2, 2])
result_multiplication = matrix * 2

print("Original Matrix:")
print(matrix)

print("Subtract [2, 2, 2]:")
print(result_subtraction)

print("Multiply by 2:")
print(result_multiplication)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Subtract [2, 2, 2]:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
Multiply by 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Linear Equation
4x + y - 2z = 10
2x - 3y + 2z = -4
x + 2y + 3z = 6

In [8]:
import numpy as np


A = np.array([[4, 1, -2],
              [2, -3, 2],
              [1, 2, 3]])
B = np.array([10, -4, 6])
X = np.linalg.solve(A, B)
print("Solution:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])


Solution:
x = 1.7999999999999998
y = 2.4
z = -0.2


If det_A is not equal to zero, it means that the system can be solved using NumPy functions because the coefficient matrix is invertible.

2x - y + 3z + 4w = 10
4x - 2y + 6z + 8w = 20
3x + y - 2z + 2w = 3
x + 3y - 4z + w = -1

In [9]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -1, 3, 4],
              [4, -2, 6, 8],
              [3, 1, -2, 2],
              [1, 3, -4, 1]])

# Constants vector B
B = np.array([10, 20, 3, -1])

# Solve for X
try:
    X = np.linalg.solve(A, B)
    print("Solution:")
    print("x =", X[0])
    print("y =", X[1])
    print("z =", X[2])
    print("w =", X[3])
except np.linalg.LinAlgError:
    print("The system of equations has no unique solution.")



The system of equations has no unique solution.


If det_A is not equal to zero, and the rank of A matches the rank of the augmented matrix [A|B], then the system can be solved using NumPy functions, and it has a unique solution.