# Lab 01

#### Submitted by : Aagnay Kariyal
#### Student ID: 8830232

HTML link to file: https://aagnaykariyal.github.io/Fall2023//students-submissions/8830232/Lab1.html

***


# Part A

***

In [1]:
import numpy as np

## Question 1

***

The code below demonstrates how to create an array that starts from the integer 1 and ends at 20, and is incremented by 3.

In [19]:
# Question 1
array_01 = np.arange(1, 20, 3)
print(f'Array with range from 1 and 20 is: \n{array_01}')

Array with range from 1 and 20 is: 
[ 1  4  7 10 13 16 19]


## Question 2

***

The following code is used to create a new array of shape 3 with random numbers between 0 and 1

In [20]:
# Question 2
array_02 = np.random.rand(3)
print(f'A new array with shape 3 with random numbers between 0 and 1:\n{array_02}')

A new array with shape 3 with random numbers between 0 and 1:
[0.79369415 0.08312174 0.05001747]


## Question 3

***

In the code block below, we create a 2D array containing 3 rows and we slice them to get the first two rows, and the last two rows as well.

In [22]:
# Question 3
array_2D = np.array([[10,20,45],[30,12,16],[42,17,56]])
print(f'Main array:\n{array_2D}\n')
# Slice for the first two rows
print(f'Slice with the first two rows:\n{array_2D[0:2]}\n')
# Slice for the last two rows
print(f'Slice with the last two rows:\n{array_2D[:0:-1]}')

Main array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

Slice with the first two rows:
[[10 20 45]
 [30 12 16]]

Slice with the last two rows:
[[42 17 56]
 [30 12 16]]


## Question 4

***

Here, we create two 2x2 arrays and we stack those elements vertically and horizontally.<br>
We then split this array further into 4 smaller arrays

In [26]:
# Question 4
array_03 = np.array([[1,2],[3,4]])
array_04 = np.array([[5,6],[7,8]])
print(f'The arrays used:\n{array_03}\n\n{array_04}\n')
# Stacking
vertical_stack = np.vstack((array_03, array_04))
horizontal_stack = np.hstack((array_03, array_04))
print('After Stacking\n')
print(f'Vertical Stack:\n{vertical_stack}\n')
print(f'Horizontal Stack:\n{horizontal_stack}\n')
split_array = np.split(vertical_stack, 4)
print(f'After splitting the array into 4 smaller arrays:\n{split_array}')

The arrays used:
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

After Stacking

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]

After splitting the array into 4 smaller arrays:
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


## Question 5

***

For the below code, we check if its possible to multiply the matrices array_x and array_y.<br>
It definitely is possible to multiply them as x contains 3 columns and y contains 3 rows.<br>
Since we multiply matrices by using the column of the first matrix and the row of the second, it works out.

The case when it would not be poissible to perform a matrix multiplication would be when the number of columns in the first matrix is not equal to the number of rows in the second matrix

In [30]:
# Question 5
array_X = ([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
array_Y = ([[4, 2], [6, 2], [4, 2]])

print('Arrays for finding the dot product:\n')
print(f'First Array:\n{array_X}\n\nSecond Array:\n{array_Y}\n')

new_array = np.dot(array_X, array_Y)
print(f'Dot product of the above arrays are:\n{new_array}')

# Error demonstration

print('\nError demonstration:')
demo_array = np.dot(array_Y, array_X)
print(demo_array)

Arrays for finding the dot product:

First Array:
[[5, 7, 2], [4, 5, 6], [7, 4, 2]]

Second Array:
[[4, 2], [6, 2], [4, 2]]

Dot product of the above arrays are:
[[70 28]
 [70 30]
 [60 26]]

Error demonstration:


ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

As you can see, the code returns a ValueError as the shapes of the arrays are not compatible to perform a matrix multiplication since, the columns of the first matrix are not in line with the rows of the second matrix


## Question 6

***

We write the below code to find the shape and dimensions of x between x and y.<br>
We also reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [14]:
# Question 06
array_X_new = np.array([2, -1, 8])
array_Y_new = np.array([3, 1, -2])
shape = array_X_new.shape
dim = array_X_new.ndim
print(f'Shape of X is {shape}, and dimension is {dim}')
# Reshaping x
array_x_reshaped = array_X_new.reshape(3,1)
print(f'The shape of the array x after reshaping is now {array_x_reshaped.shape}')
# Reshaping Y
array_y_reshaped = array_Y_new.reshape(3,1)
print(f'The dimension of y after reshaping is now {array_y_reshaped.ndim}')

Shape of X is (3,), and dimension is 1
The shape of the array x after reshaping is now (3, 1)
The dimension of y after reshaping is now 2


## Question 7

***

Broadcasting is a way of performing element wise operations on arrays with different shapes provided that they follow the compatibility rules

In the code below, we try broadcasting by subtracting and multiplying 5 on a 3x3 matrix to demonstrate broadcasting.

In [16]:
# Question 7
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
subtraction = matrix - 5
multiplication = matrix * 5

print(f'Main matrix : \n{matrix},\n\nAfter subtraction of 5:\n{subtraction},\n\nAfter multiplication of 5:\n{multiplication}')

Main matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]],

After subtraction of 5:
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]],

After multiplication of 5:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


# PART B

***

## Part B.1

***

In the below code chunk we first check the singularity of the following linear equations:

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

We check for the singularity by finding the determinant of the equations.<br> 
We use the numpy functions to find the determinant first.<br>
Since the determinant of the equations are of a non-singular system, we can solve this system of linear equations using numpy.

In [32]:
# Question B1
a = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])
b = np.array([10,4,6])
det = np.linalg.det(a)
print(f'The determinant of the above equations are: {det}\n')
ans = np.linalg.solve(a,b)
print(f'The solutions for x,y and z are as follows: {ans}\n')

The determinant of the above equations are: -70.00000000000003

The solutions for x,y and z are as follows: [2.6 0.8 0.6]



## Part B.2

***

We cannot solve the following equations:

1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

as the equations are of a singular system. <br>
We found out that the system is singular and by checking for the determinant of the system, and since the determinant of the system is 0, the system is singular and cannot be solved using numpy functions.

In [34]:
# Question B2
c = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])
sol = np.linalg.det(c)
print(f'The determinants of the above equations are: {sol}')
print('Hence, they are singular systems and cannot be solved.')

The determinants of the above equations are: 0.0
Hence, they are singular systems and cannot be solved.
