In [4]:
import numpy as np
#array of 20 elements each incremented by 3
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [9]:

import numpy as np
#rand gives 1D array if one parameter passed between 0 to 1
r1 = np.random.rand(3)
print("1D : ", r1)

#rand gives 2D array if 2 parameter passed between 0 to 1
r2 = np.random.rand(3,3)
print("2D : ", r2)

#rand gives 3D array if 3 parameter passed between 0 to 1
r3 = np.random.rand(4,3,2)
print("3D : ", r3)

print(np.shape(r3))


rand=np.random.randint(1,6)
print("Random number: ",rand)                                                                

1D :  [0.33476836 0.5480316  0.98617984]
2D :  [[0.94420724 0.37405892 0.69599829]
 [0.44965667 0.77883185 0.44081186]
 [0.42136383 0.90253656 0.58582271]]
3D :  [[[0.49263978 0.98774809]
  [0.32038323 0.96704844]
  [0.6827182  0.75681492]]

 [[0.87423835 0.92871553]
  [0.36514884 0.48760953]
  [0.88179386 0.89463699]]

 [[0.35534354 0.37719995]
  [0.58863911 0.82486844]
  [0.754201   0.86767886]]

 [[0.7573605  0.89116327]
  [0.62107491 0.30573366]
  [0.65690756 0.97577798]]]
(4, 3, 2)
Random number:  1


In [35]:
x=np.array([[10,20,45], [30,12,16], [42,17,56]])
print("first two rows: ", x[0:2])
print("last two rows: ",x[1:])
print("last two rows and last two columns: ",x[1:,1:])
print("first two rows and last two columns: ",x[:2,1:])

first two rows:  [[10 20 45]
 [30 12 16]]
last two rows:  [[30 12 16]
 [42 17 56]]
last two rows and last two columns:  [[12 16]
 [17 56]]
first two rows and last two columns:  [[20 45]
 [12 16]]


In [10]:
x=np.random.randint(1,15,size=(2,2))
y=np.random.randint(100,150,size=(2,2))

horstack= np.hstack((x,y))
print("horz stack: ",horstack)

verstack= np.vstack((x,y))
print("vert stack: ",verstack)

horz stack:  [[  7   4 137 146]
 [  5  10 131 134]]
vert stack:  [[  7   4]
 [  5  10]
 [137 146]
 [131 134]]


In [16]:
X= np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) 
Y= np.array([[4, 2], [6, 2], [4, 2]])
product=np.dot(X,Y)
print(product)
#print(X@Y)
#Multiplication is not possible when the columns of matrix 1 is not equal to rows of matrix 2.

[[70 28]
 [70 30]
 [60 26]]
[[70 28]
 [70 30]
 [60 26]]


In [20]:
x=np.array([2,-1,-8])
y=np.array([3,1,-2])

xshape=x.shape
xdim=x.ndim

print("x shape=", xshape)
print("x dimension= ",xdim)

xreshape=x.reshape(3,1)
print("xreshape=",xreshape)

yshape=y.shape
ydim=y.ndim

print("y shape=", yshape)
print("y dimension= ",ydim)

yreshape=y.reshape(3,1)
print(yreshape)

x shape= (3,)
x dimension=  1
xreshape= [[ 2]
 [-1]
 [-8]]
y shape= (3,)
y dimension=  1
[[ 3]
 [ 1]
 [-2]]


In [18]:
import numpy as np

# Create a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Subtract/multiply/adding 2 from each element using broadcasting
sub = A - 2
add= A+2
mul = A*2

print("subtract",sub)
print("addition",add)
print("multiply",mul)

subtract [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
addition [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
multiply [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
