In [4]:
import numpy as np
#array of 20 elements each incremented by 3
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [24]:

#rand gives 1D array if one parameter passed between 0 to 1
r1 = np.random.rand(3)
print("1D : ", r1)

#rand gives 2D array if 2 parameter passed between 0 to 1
r2 = np.random.rand(3,2)
print("2D : ", r2)

#rand gives 3D array if 3 parameter passed between 0 to 1
r3 = np.random.rand(4,3,2)
print("3D : ", r3)

rand=np.random.randint(1,6)
print("Random number: ",rand)

1D :  [0.25340493 0.63172816 0.72876427]
2D :  [[0.05218434 0.10490651]
 [0.75224389 0.1224776 ]
 [0.52328618 0.26710371]]
3D :  [[[0.53560391 0.49204955]
  [0.48069732 0.60949136]
  [0.17578412 0.4478645 ]]

 [[0.25803417 0.01148351]
  [0.52009666 0.30995644]
  [0.51259818 0.91644321]]

 [[0.04200161 0.60034018]
  [0.54203164 0.78153213]
  [0.05398004 0.88062021]]

 [[0.1345915  0.45173578]
  [0.28918458 0.30467435]
  [0.13296357 0.77596036]]]
5


In [35]:
x=np.array([[10,20,45], [30,12,16], [42,17,56]])
print("first two rows: ", x[:2])
print("last two rows: ",x[1:])
print("last two rows and last two columns: ",x[1:,1:])
print("first two rows and last two columns: ",x[:2,1:])

first two rows:  [[10 20 45]
 [30 12 16]]
last two rows:  [[30 12 16]
 [42 17 56]]
last two rows and last two columns:  [[12 16]
 [17 56]]
first two rows and last two columns:  [[20 45]
 [12 16]]


In [44]:
x=np.random.randint(1,15,size=(2,2))
y=np.random.randint(100,150,size=(2,2))

horstack= np.hstack((x,y))
print("horz stack: ",horstack)

verstack= np.vstack((x,y))
print("vert stack: ",verstack)

horz stack:  [[ 10   5 104 131]
 [  4  10 139 108]]
vert stack:  [[ 10   5]
 [  4  10]
 [104 131]
 [139 108]]
