# **Lab 1 Assignment - AI algorithms - Numpy**

## Aneesh Krishna Ramesh - 8914620


In [89]:
import numpy as np 

### 1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [90]:

array = np.arange(1,21,3)

print(array)

[ 1  4  7 10 13 16 19]


###  2. Create a new array of shape 3 with random numbers between 0 and 1.

In [91]:
npArray = np.random.rand(3)
print(npArray)

[0.89789247 0.44163744 0.51634008]


###  3. Create a 2-D array `[[10,20,45], [30,12,16], [42,17,56]]` and perform the following operations: 
####	 - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [104]:
# First 2 Row Split
twoDArray = np.array([[10,20,45], [30,12,16], [42,17,56]]);
print("Original 2d array : \n",twoDArray,"\n")

first_rows = twoDArray[:2, :]
print("Split array : \n",first_rows)

Original 2d array : 
 [[10 20 45]
 [30 12 16]
 [42 17 56]] 

Split array : 
 [[10 20 45]
 [30 12 16]]


In [93]:
# Last 2 Row Split
last_rows = twoDArray[1:3, :]
print(last_rows)

[[30 12 16]
 [42 17 56]]


###  4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [94]:
twoDArrayOne = np.array([[1, 2],[3, 4]])
twoDArrayTwo = np.array([[5, 6],[7, 8]])

verticalStackedArray = np.vstack((twoDArrayOne, twoDArrayTwo))
print(verticalStackedArray)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [95]:
horStackedArray = np.hstack((twoDArrayOne, twoDArrayTwo))
print(horStackedArray)

[[1 2 5 6]
 [3 4 7 8]]


In [100]:
# and split the arrays into smaller arrays.
twoDArrayOne = np.vsplit(verticalStackedArray,4)
twoDArrayTwo = np.hsplit(verticalStackedArray,2)

print("Split arrays are : ",twoDArrayOne)


Split arrays are :  [array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]



## Part A- Create a Notebook to demonstrate NumPy Operations.

### 5. Create two matrices `X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]),   Y= ([[4, 2], [6, 2], [4, 2]])` 
#####	 - Is it possible to multiply these matrices? 
#####	 - Demonstrate the case when it is not possible to.

> **ANSWER** : The matrices can be multiplied because the first matrix is a 3x3 and the 2nd is a 3x2. Since the number of columns in the 1st matrix is the same as the number of rows in the 2nd matrix which can be seen below. 

In [97]:
twoDArrayOne = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
twoDArrayTwo = np.array([[4, 2], [6, 2], [4, 2]])
multipliedMatrix = np.dot(twoDArrayOne,twoDArrayTwo)

print(multipliedMatrix)


[[70 28]
 [70 30]
 [60 26]]


> **ANSWER** :  It cannot be multiplied if the columns in matrix A and columns in matrix B don't match. As demonstrated below. 

**ERROR-EXPECTED BELOW**

In [98]:
# ERROR EXPECTED in running below 
twoDArrayOne = np.array([[5, 7, 2,1], [4, 5, 6,1], [7, 4 ,2,1]])
twoDArrayTwo = np.array([[4, 2], [6, 2], [4, 2]])
multipliedMatrix = np.dot(twoDArrayOne,twoDArrayTwo)

print(multipliedMatrix)

ValueError: shapes (3,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

### 6. Create two arrays, `x = ([2, -1, -8]) y = ([3, 1, -2]),`
#####	 - Find the Shape, Number of dimensions of vector x.
#####	 - Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [ ]:
twoDArrayOne = np.array([2, -1, -8])
twoDArrayTwo = np.array([3, 1, -2])

print("Vector 1 : Shape :",twoDArrayOne.shape,", Dimension :",twoDArrayOne.ndim)
print("Vector 2 : Shape :",twoDArrayTwo.shape,", Dimension :",twoDArrayTwo.ndim)

Vector 1 : Shape : (3,) , Dimension : 1
Vector 2 : Shape : (3,) , Dimension : 1


### 7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

> **ANSWER** : Broadcasting allows us to perform multiple operations like addition, multiplication throughout an array without looping over each element. The name broadcasting comes from how NumPy handles these operations, it essentially broadcasts a small  array in the larger array to turn them into compatible shapes. 
> The below example shows examples of Substraction and Multiplication

In [ ]:
twoDArrayOne = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
twoDArrayTwo = np.array([[10, 11, 12],[13, 14, 15],[16, 17, 18]])
subArray = twoDArrayOne - twoDArrayTwo 
mulArray = twoDArrayOne * twoDArrayTwo

print(subArray,"\n")
print(mulArray,"\n")


[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]] 

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]] 



In [ ]:
# With broadcasting
print(twoDArrayOne - np.array([1,2,9]).reshape(1,3),"\n")
print(twoDArrayOne * np.array([1,2,9]).reshape(3,1) )

[[ 0  0 -6]
 [ 3  3 -3]
 [ 6  6  0]] 

[[ 1  2  3]
 [ 8 10 12]
 [63 72 81]]


## **Part B- Linear Equations**
Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.
### Part B.1

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

In [99]:
matrix = np.array([[4, 1, -2],[2, -3, 2],[1, 2, 3]])
det = np.linalg.det(matrix)
print("determinant of matrix : ",det)


determinant of matrix :  -70.00000000000003


>  **ANSWER** :  Since the Determinant of the above system of equations is non-Zero (~ -70), the result is that the system is **NON-SINGULAR** 
> & hence has a unique solution. 

> Hence this **CAN** be solved by using numpy as shown below

In [ ]:
sum = np.array([10, -4, 6])
mulSolution = np.linalg.solve(matrix, sum)
print("values of x, y & z ::: ",mulSolution)

values of x, y & z :::  [ 1.8  2.4 -0.2]


### Part B.2    
		
1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [ ]:
matrix = np.array([[2,-1,3,4],[4, -2, 6, 8],[3, 1, -2, 2],[1,3,-4, 1]])
det = np.linalg.det(matrix)
print("determinant of matrix : ",det)

0.0


>  **ANSWER** : Since the Determinant of the above system of equations **IS ZERO**, the result is that the system is **SINGULAR** 
> & hence has a NO unique solution or Infinite solutions. 

> So, this **CANNOT** be solved using Numpy as it only accepts a Non-Singular matrix, as shown below 

**ERROR-EXPECTED BELOW**

In [ ]:
sum = np.array([10, 20, 3, -1])
mulSolution = np.linalg.solve(matrix, sum)
print("values of x, y, z & w ::: ",mulSolution)

LinAlgError: Singular matrix