# Part - A
## Import numpy and Array operations
### - Creating an array
### - Creating array of shape 3 with random numbers
### - Creating an 2D array
### - Slicing the 2D array

In [34]:
import numpy as np

# Create an array from 1 to 20 incremented by 3
array1 = np.arange(1, 21, 3)

# Create a new array of shape 3 with random numbers between 0 and 1
random_array = np.random.rand(3)

# Create a 2D array
matrix = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# Slice the 2D array to get the first two rows
first_two_rows = matrix[:2, :]

# Slice the 2D array to get the last two rows
last_two_rows = matrix[1:, :]

print("Array 1:", array1)
print("Random Array:", random_array)
print("Matrix:")
print(matrix)
print("First Two Rows:")
print(first_two_rows)
print("Last Two Rows:")
print(last_two_rows)



Array 1: [ 1  4  7 10 13 16 19]
Random Array: [0.56682931 0.68983976 0.08515414]
Matrix:
[[10 20 45]
 [30 12 16]
 [42 17 56]]
First Two Rows:
[[10 20 45]
 [30 12 16]]
Last Two Rows:
[[30 12 16]
 [42 17 56]]


### Creating two 2x2 arrays
### Stacking the arrays vertically
### Stacking the arrays horizontally
### Spliting the array into smaller arrays

In [35]:
# Create two 2x2 arrays
array2 = np.array([[1, 2], [3, 4]])
array3 = np.array([[5, 6], [7, 8]])

# Stack the arrays vertically
vertical_stack = np.vstack((array2, array3))

# Stack the arrays horizontally
horizontal_stack = np.hstack((array2, array3))

# Split the arrays into smaller arrays
split_array2 = np.split(array2, 2)
split_array3 = np.split(array3, 2)

print("Array 2")
print(array2)
print("Array 3")
print(array3)
print("Vertical Stack:")
print(vertical_stack)
print("Horizontal Stack:")
print(horizontal_stack)
print("Split Array 2:")
print(split_array2)
print("Split Array 3:")
print(split_array3)


Array 2
[[1 2]
 [3 4]]
Array 3
[[5 6]
 [7 8]]
Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]
Split Array 2:
[array([[1, 2]]), array([[3, 4]])]
Split Array 3:
[array([[5, 6]]), array([[7, 8]])]


### Creating Matrices X and Y
### Checking the possible to multiply X and Y

In [36]:
# Create matrices X and Y
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Check if it's possible to multiply X and Y
if X.shape[1] == Y.shape[0]:
    multiplication_result = np.dot(X, Y)
else:
    multiplication_result = "Matrix multiplication is not possible."

print("Matrix X:")
print(X)
print("Matrix Y:")
print(Y)
print("Matrix Multiplication Result:")
print(multiplication_result)



Matrix X:
[[5 7 2]
 [4 5 6]
 [7 4 2]]
Matrix Y:
[[4 2]
 [6 2]
 [4 2]]
Matrix Multiplication Result:
[[70 28]
 [70 30]
 [60 26]]


### Creating two arrays, x and y
### Finding the shape and number of dimensions of vector x
### Reshape the vector x to a matrix of size (3,1)
### Determining the number of dimensions after reshaping y to a matrix of (3,1)

In [37]:
# Create two arrays, x and y
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Find the shape and number of dimensions of vector x
x_shape = x.shape
x_dimensions = x.ndim

# Reshape vector x to a matrix of size (3, 1)
x_reshaped = x.reshape(3, 1)

# Determine the number of dimensions after reshaping y to a matrix of (3, 1)
y_reshaped = y.reshape(3, 1)
y_reshaped_dimensions = y_reshaped.ndim

print("Vector x Shape:", x_shape)
print("Vector x Number of Dimensions:", x_dimensions)
print("Reshaped Vector x:")
print(x_reshaped)
print("Number of Dimensions after Reshaping y:", y_reshaped_dimensions)


Vector x Shape: (3,)
Vector x Number of Dimensions: 1
Reshaped Vector x:
[[ 2]
 [-1]
 [-8]]
Number of Dimensions after Reshaping y: 2


### Broadcasting : Subtraction and Multiplication by 3x3 matrix

In [38]:
# Broadcasting: Demonstrate subtraction and multiplication by considering a 3x3 matrix
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalar = 10

# Broadcasting subtraction
result_subtraction = matrix_a - scalar

# Broadcasting multiplication
result_multiplication = matrix_a * scalar

print("Broadcasting Subtraction:")
print(result_subtraction)
print("Broadcasting Multiplication:")
print(result_multiplication)

Broadcasting Subtraction:
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
Broadcasting Multiplication:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


# Part - B - Linear Equations
### Part B.1
### 4x + y - 2z = 10
### 2x - 3y + 2z = -4
### x + 2y + 3z = 6


In [39]:
# Matrix b1
matrix_b1 = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])

# Right-hand side constants
constants_b1 = np.array([10, -4, 6])

# Check the determinant of the coefficient matrix
determinant_b1 = np.linalg.det(matrix_b1)

# Determine if the system is singular
if determinant_b1 != 0:
    # The system has a unique solution
    solution_b1 = np.linalg.solve(matrix_b1, constants_b1)
else:
    # The system is singular, and the solution may not exist or be non-unique
    solution_b1 = "No unique solution (system is singular)"

print("Determinant of matrix B.1:", round(determinant_b1,2))
print("Solution B.1:", solution_b1)


Determinant of matrix B.1: -70.0
Solution B.1: [ 1.8  2.4 -0.2]


### Part B.2
### 2x - y + 3z + 4w = 10
### 4x - 2y + 6z + 8w = 20
### 3x + y - 2z + 2w = 3
### x + 3y - 4z + w = -1


In [41]:
# Matrix b2
matrix_b2 = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])

# Right-hand side constants
constants_b2 = np.array([10, 20, 3, -1])

# Check the determinant of the coefficient matrix
determinant_b2 = np.linalg.det(matrix_b2)

# Determine if the system is singular
if determinant_b2 != 0:
    # The system has a unique solution
    solution_b2 = np.linalg.solve(matrix_b2, constants_b2)
else:
    # The system is singular, and the solution may not exist or be non-unique
    solution_b2 = "No unique solution (system is singular)"

print("Determinant of matrix B.2:", determinant_b2)
print("Solution B.2:", solution_b2)


Determinant of matrix B.2: 0.0
Solution B.2: No unique solution (system is singular)
