#### import numPy

In [1]:
import numpy as np

## Part A

1. Create an array that starts from the integer 1, ends at 20, incremented by 3.
 

In [2]:
numpyArrOfElements = np.arange(start=1,stop=20, step=3)

2. Create a new array of shape 3 with random numbers between 0 and 1.
 

In [8]:
rand_int = np.random.randn(1,3) 
print(rand_int)

[[ 1.32097276 -0.44874316  0.06624509]]


3. Create a 2 D array `[[10,20,45], [30,12,16], [42,17,56]]` and perform the following operations: 
	 - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.
 

In [13]:
twoDarray=[[10,20,45], [30,12,16], [42,17,56]]
numpy2D = np.array(twoDarray)
print(numpy2D[:2])
print(numpy2D[-2:])


[[30 12 16]
 [42 17 56]]
[[10 20 45]
 [30 12 16]]


4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
 

In [16]:
a = np.array([[1, 2],[3,4]])
b = np.array([[ 5, 6],[7,8]])
c=np.vstack((a,b))
d=np.hstack((a,b))
print(c,d)
e=np.array_split(c,4)
print(e)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] [[1 2 5 6]
 [3 4 7 8]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


5. Create two matrices `X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),` 
	 - Is it possible to multiply these matrices? 
	 - Demonstrate the case when it is not possible to.
 

In [19]:
X= [[5, 7, 2], [4, 5, 6], [7, 4 ,2]]
Y= [[4, 2], [6, 2], [4, 2]]
Z=np.matmul(X,Y)
ZZ=np.matmul(Y,X)
print(Z)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

 ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

6. Create two arrays, `x = ([2, -1, -8]) y = ([3, 1, -2]),`
	 - Find the Shape, Number of dimensions of vector x.
	 - Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).


In [25]:
x = np.array([2, -1, -8])
y = [3, 1, -2]

print(x.ndim,x.shape)
xx=np.reshape(x,(3,1))
yy=np.reshape(y,(3,1))
print(xx)
print(yy.ndim)

1 (3,)
[[ 2]
 [-1]
 [-8]]
2


 7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [38]:
m3by3=np.arange(9).reshape(3,3)
print(m3by3-5)
print(m3by3*[5,2,1])
M = np.ones((3, 3))
M=M*5
print(m3by3,"-",M,"=",m3by3-M)
d=np.array([5,2,1])
dd=np.tile(d,(3,1)).reshape(3,3)
print(m3by3,"*",dd,"=",m3by3*dd)




[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
[[ 0  2  2]
 [15  8  5]
 [30 14  8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]] - [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]] = [[-5. -4. -3.]
 [-2. -1.  0.]
 [ 1.  2.  3.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]] * [[5 2 1]
 [5 2 1]
 [5 2 1]] = [[ 0  2  2]
 [15  8  5]
 [30 14  8]]


## Part B.1

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

which is non-singular



In [39]:
a=np.array([[4,1,-2],[2,-3,2],[1,2,3]])
b=np.array([10,-4,6])
print(np.linalg.solve(a,b))

[ 1.8  2.4 -0.2]


## Part B.2    		
1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

which is singular because eq2=2*eq1

In [40]:
a=np.array([[2,-1,3,4],[4,-2,6,8],[3,1,-2,2],[1,3,-4,1]])
b=np.array([10,20,3,-1])
print(np.linalg.solve(a,b))

LinAlgError: Singular matrix