# CSCN8000 Lab-1
Name: Devanshi Joshi   
Id: 8868052  

#### Part-A - Demonstrating NumPy Operations 

In [2]:
# Importing the necessary libraries required 
import numpy as np

1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
array1 = np.arange(1, 21, 3)
print(array1)

[ 1  4  7 10 13 16 19]


The above code uses the np.arange function. The np.arange function is used to create an array of evenly spaced values within a specified range which in our case is from 1 to 20.

2. Create a new array of shape 3 with random numbers between 0 and 1.

In [3]:
array2 = np.random.rand(3)
print(array2)

[0.93242338 0.03698687 0.69074013]


The above code uses the np.random.rand(3) function that generates 3 random float numbers between 0 (inclusive) and 1 (exclusive).

3. Create a 2D array [[10,20,45], [30,12,16], [42,17,56]] and perform the requested operations.   
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [4]:
array3 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# Slice the 2D array to get the first two rows
first_two_rows = array3[:2, :]

# Slice the 2D array to get the last two rows
last_two_rows = array3[1:, :]

print("First two rows:")
print(first_two_rows)

print("Last two rows:")
print(last_two_rows)


First two rows:
[[10 20 45]
 [30 12 16]]
Last two rows:
[[30 12 16]
 [42 17 56]]


I have defined an array which has 3 rows and 3 columns. I have used slicing to extract the first two and the last two rows of the array.

4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [16]:
array4 = np.array([[12, 35], [23, 42]])
array5 = np.array([[25, 32], [17, 28]])

# Stack vertically
stacked_vertically = np.vstack((array4, array5))

# Stack horizontally
stacked_horizontally = np.hstack((array4, array5))

# Split the arrays
split_vertically = np.split(stacked_vertically, 2)
split_horizontally = np.split(stacked_horizontally, 2)

print("Stacked vertically:")
print(stacked_vertically)

print("Stacked horizontally:")
print(stacked_horizontally)

print("Split vertically:")
print(split_vertically)

print("Split horizontally:")
print(split_horizontally)


Stacked vertically:
[[12 35]
 [23 42]
 [25 32]
 [17 28]]
Stacked horizontally:
[[12 35 25 32]
 [23 42 17 28]]
Split vertically:
[array([[12, 35],
       [23, 42]]), array([[25, 32],
       [17, 28]])]
Split horizontally:
[array([[12, 35, 25, 32]]), array([[23, 42, 17, 28]])]


Two 2x2 arrays have been defined for this example.   
The function vstack is used to stack the arrays vertidcally which results in a 4x2 matrix.   
The function hstack is used to stack the arrays horizontally which results in a 2x4 matrix.   
For splitting the matrix vertically and horizontally the split function has been used. 

5. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]])   
- Is it possible to multiply these matrices?   

In [7]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Check if multiplication is possible
if X.shape[1] == Y.shape[0]:
    result = np.dot(X, Y)
    print("Matrix multiplication is possible.")
    print("Result:")
    print(result)
else:
    print("Matrix multiplication is not possible.")


Matrix multiplication is possible.
Result:
[[70 28]
 [70 30]
 [60 26]]


This code checks if matrix multiplication between matrices X and Y is possible. X is a 3x3 matrix and Y is a 3x2 matrix. As per the mulitplication rule the number of columns in the first matrix should be equal to the number of rows in the second matrix. 

- Demonstrate the case when it is not possible to.

In [13]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Reshaping the arrays X and Y to demonstrate a case where matrix multiplication is not possible
X_reshaped = X.reshape(9, 1)  
Y_reshaped = Y.reshape(3, 2)  

# Condition to check if matrix multiplication is possible
if X_reshaped.shape[1] == Y_reshaped.shape[0]:
    result = np.dot(X_reshaped, Y_reshaped)
    print("Matrix multiplication is possible.")
    print("Result:")
    print(result)
else:
    print("Matrix multiplication is not possible.")


Matrix multiplication is not possible.


For demonstrating the case where matrix multiplication is not possible I have reshaped the matrix X as a 9x1 matrix and Y as a 3x2 matrix. The number of columns in the first matrix is 1 and the number of rows in the second matrix is 3. The reshaping of the matrix enables the demonstration of the case where the matrix multiplication is not possible.  

6. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
- Find the Shape, Number of dimensions of vector x.
- Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).


In [14]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Finding the shape and number of dimensions of vector x
x_shape = x.shape
x_dims = x.ndim

# Reshaping x to a matrix of size (3, 1)
x_reshaped = x.reshape(3, 1)

# Reshaping y to a matrix of size (3, 1) and determining the number of dimensions
y_reshaped = y.reshape(3, 1)
y_reshaped_dims = y_reshaped.ndim

# Printing the results 
print("Shape of x:", x_shape)
print("Number of dimensions of x:", x_dims)
print("Reshaped x:")
print(x_reshaped)
print("Number of dimensions of reshaped y:", y_reshaped_dims)


Shape of x: (3,)
Number of dimensions of x: 1
Reshaped x:
[[ 2]
 [-1]
 [-8]]
Number of dimensions of reshaped y: 2


The code will display the shape and number of dimensions of vector x. and reshape both x and y into matrices of size (3, 1) and determine the number of dimensions of the reshaped y.

7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [15]:
matrix_a = np.array([[11, 2, 31], [14, 5, 16], [7, 18, 29]])
scalar_b = 2

# Subtract scalar_b from each element of matrix_a
result_subtraction = matrix_a - scalar_b

# Multiply each element of matrix_a by scalar_b
result_multiplication = matrix_a * scalar_b

print("Matrix A:")
print(matrix_a)

print("Subtracting a scalar:")
print(result_subtraction)

print("Multiplying by a scalar:")
print(result_multiplication)


Matrix A:
[[11  2 31]
 [14  5 16]
 [ 7 18 29]]
Subtracting a scalar:
[[ 9  0 29]
 [12  3 14]
 [ 5 16 27]]
Multiplying by a scalar:
[[22  4 62]
 [28 10 32]
 [14 36 58]]


NumPy's broadcasting feature enables element-wise operations on various array forms. For the element-wise operation in broadcasting, the scalar is automatically expanded to take the shape of the matrix.   
The code subtracts the scalar value scalar_b (which is 2) from each element of matrix_a, creating a new matrix result_subtraction with the same dimensions as matrix_a. Further it multiplies each element of matrix_a by the scalar value scalar_b, creating a new matrix result_multiplication with the same dimensions as matrix_a.

#### Part-B - Linear Equations 
##### Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.
##### Part-B.1


    4x + y - 2z = 10
    2x - 3y + 2z = -4
    x + 2y + 3z = 6
    


To determine the singularity of the system i.e., if it has a unique solution, we can use the determinant of matrix A. 
- If the determinant of matrix A is non-zero, the system has a unique solution. 
- If the determinant is zero, the system is singular and may have either no solutions or infinitely many solutions.

If the determinant of A is non-zero, the code will print that the system is not singular and will provide the unique solution using NumPy's linalg.solve function. Otherwise, it will print that the system is singular, indicating that there may be no solutions or infinitely many solutions.

In [4]:
A = np.array([[4, 1, -2],
              [2, -3, 2],
              [1, 2, 3]])

# Finding the determinant of the matrix A 
det_A = np.linalg.det(A)

if det_A != 0:
    print("The system is not singular, and it has a unique solution.")
    b = np.array([10, -4, 6])
    x = np.linalg.solve(A, b)
    print("Solution (x, y, z):", x)
else:
    print("The system is singular, and it may have either no solutions or infinitely many solutions.")

The system is not singular, and it has a unique solution.
Solution (x, y, z): [ 1.8  2.4 -0.2]


The solution that was provided concludes the the value of x = 1.8, y = 2.4 and z = -0.2   
When the values are substituted in the original linear equations the results obtained confirm that the values are correct  
 
    4(1.8) + 2.4 -2(-0.2) = 7.2 + 2.4 + 0.4 = 10   
    2(1.8) - 3(2.4) + 2(-0.2) = 3.6 - 7.2 - 0.4 = -4   
    1.8 + 2(2.4) + 3(-0.2) = 1.8 + 4.8 - 0.6 = 6   

##### Part-B.2

    2x - y + 3z + 4w = 10
    4x - 2y + 6z + 8w = 20
    3x + y - 2z + 2w = 3
    x + 3y - 4z + w = -1


In [8]:
A = np.array([[2, -1, 3, 4],
              [4, -2, 6, 8],
              [3, 1, -2, 2],
              [1, 3, -4, 1]])

# Calculate the determinant of A
det_A = np.linalg.det(A)
if det_A != 0:
    print("The system is not singular, and it has a unique solution.")
    b = np.array([10, 20, 3, -1])
    x = np.linalg.solve(A, b)
    print("Solution (x, y, z, w):", x)
else:
    print("The system is singular, and it may have either no solutions or infinitely many solutions.")


The system is singular, and it may have either no solutions or infinitely many solutions.


The message "The system is singular, and it may have either no solutions or infinitely many solutions" indicates that matrix A of the system is singular, which denotes that its determinant is zero. When the determinant of the matrix is zero, it indicates that the system of equations may have multiple solutions, or it may be inconsistent (no solutions).   
A system of linear equations with a singular matrix (zero determinant) indicates that the columns are linearly dependent, leading to an underdetermined system. Infinite solutions occur when the system has infinitely many solutions, resulting in multiple sets of variables satisfying the equations simultaneously. This is underdetermined because there are more variables than independent equations. Traditional Gaussian elimination or numpy's linalg.solve function cannot find a unique solution due to the infinite number of solutions. Instead, a square matrix with a non-zero determinant is needed to find a unique solution.