# Name: Samarth Subhash Deshpande

# Student ID: 8894058

In [ ]:
Importing necessary packages 

In [1]:
import numpy as np
import pandas as pd

# Part A- Create a Notebook to demonstrate NumPy Operations.

# Q1) Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [5]:
# The numpy arange function is used to create an array in a specified range.[np.arange(start,stop,step)]
array = np.arange(1,20,3)
print("The incremented by 3 numbers",array)

The incremented by 3 numbers [ 1  4  7 10 13 16 19]


# Q2) Create a new array of shape 3 with random numbers between 0 and 1.

In [6]:
# np.random.rand() function is used to generate random numbers 
array1 = np.random.rand(3)
array1

array([0.8515035 , 0.2460776 , 0.55720139])

# Q3) Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [9]:
# Creating a 2D array
array2 = np.array([[10,20,45],[30,12,16],[42,17,56]])
array2
#slicing first two rows
first_two_rows = array2[:2,:]
#slcing last two rows
last_two_rows = array2[1:,:]

In [10]:
print("The first two rows are ","\n",first_two_rows)

The first two rows are  
 [[10 20 45]
 [30 12 16]]


In [11]:
print("The Last two rows are","\n",last_two_rows)

The Last two rows are 
 [[30 12 16]
 [42 17 56]]


# Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [19]:
array1 = np.array([[100,101], [102,103]])
array2 = np.array([[104,105], [106,107]])

In [20]:
print("The array1 is","\n",array1)

The array1 is 
 [[100 101]
 [102 103]]


In [14]:
print("the array2 is","\n",array2)

the array2 is 
 [[104 105]
 [106 107]]


In [43]:
#vertical stack
# vstack is a function that is used to vertically stack arrays
arr3_vstack = np.vstack((array1,array2))
print("The vertical stack is","\n",arr3_vstack)

The vertical stack is 
 [[100 101]
 [102 103]
 [104 105]
 [106 107]]


In [44]:
#horizontal stack
# hstack is a function that is used to horizontally stack arrays
arr4_hstack = np.hstack((array1,array2))
print("The horizontal stack is","\n",arr4_hstack)

The horizontal stack is 
 [[100 101 104 105]
 [102 103 106 107]]


In [17]:
#create a vertical split of the given arrays
vert_split = np.vsplit(arr_3_vstack,2)
print("Vertical splits is","\n",vert_split)

Vertical splits is 
 [array([[100, 101],
       [102, 103]]), array([[104, 105],
       [106, 107]])]


In [18]:
#create horizontal split of the given arrays
horizontal_split = np.hsplit(arr_4_hstack,4)
print("The horizontal split is","\n",horizontal_split)

The horizontal split is 
 [array([[100],
       [102]]), array([[101],
       [103]]), array([[104],
       [106]]), array([[105],
       [107]])]


# Q5.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices

We can perform the matrix multiplication of the above given two matrices using matmul.can handle matrix multiplication for arrays of various dimensions and shapes.

In [45]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])
multi_matrices = np.matmul(X, Y)
print("The multiplied matrices are","\n",multi_matrices)

The multiplied matrices are 
 [[70 28]
 [70 30]
 [60 26]]


# Q6 .Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x

In [22]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])
#Shape OF X and Y
x_shape = x.shape
y_shape = y.shape
#Dimension of vector x and y
x_dim = x.ndim
y_dim = y.ndim

In [23]:
print("The shape of x is", x_shape)
print("The shape of y is:", y_shape)
print("Number of dimensions of x:", x_dim)
print("Number of dimensions of y:", y_dim)

The shape of x is (3,)
The shape of y is: (3,)
Number of dimensions of x: 1
Number of dimensions of y: 1


In [24]:
reshape_x = print("Reshaping x","\n",x.reshape(3,1))
reshape_y = print("Reshaping y","\n",y.reshape(3,1))

Reshaping x 
 [[ 2]
 [-1]
 [-8]]
Reshaping y 
 [[ 3]
 [ 1]
 [-2]]


# Q7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [ ]:
Broadcasting enables us to performing operations between arrays of different shapes

In [57]:
a = np.array([[120,130 ,140],[150, 160, 170],[180, 190, 210]])
print("Matrix 1 is","\n",a)

b = np.array([[110,120,130],[140,150,160],[170,180,190]])
print("Matrix 2 is","\n",b)

Matrix 1 is 
 [[120 130 140]
 [150 160 170]
 [180 190 210]]
Matrix 2 is 
 [[110 120 130]
 [140 150 160]
 [170 180 190]]


In [49]:
# Subtraction of a and b
sub = a - b
sub

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 20]])

In [50]:
#Multipilcation of a and b
multi = np.dot(a,b)
multi

array([[55200, 59100, 63000],
       [67800, 72600, 77400],
       [82100, 87900, 93700]])

# Part B- Linear Equations

Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible.Justify the reason why you believe the system can or cannot be solved using numpy functions.

Part B.1
4x + y - 2z = 10
2x - 3y + 2z = -4
x + 2y + 3z = 6

In [55]:
X = np.array([[4, 1, -2],[2, -3, 2],[1, 2, 3]])
Y = np.array([10, -4, 6])

In [54]:
#Calculate determinant of A
detX = np.linalg.det(X)
detX

-70.00000000000003

In [53]:
sol=np.linalg.solve(X,Y)
sol

array([ 1.8,  2.4, -0.2])

# Ans) detX is not equal to 0 so matrix X is not singular.we can expected to have a unique solution

Part B.2
2x - y + 3z + 4w = 10
4x - 2y + 6z + 8w = 20
3x + y - 2z + 2w = 3
x + 3y - 4z + w = -1

In [56]:
E = np.array([[2, -1, 3, 4],[4, -2, 6, 8],[3, 1, -2, 2],[1, 3, -4, 1]])
F = np.array([10, 20, 3, -1])

In [51]:
#Calculate determinant of A
detE = np.linalg.det(E)
detE

0.0

# Ans) detX is equal to 0 so matrix A is singular. we cannot expected to have unique solution

In [40]:
sol1=np.linalg.solve(E,F)
sol1

LinAlgError: Singular matrix

It is a singular matrix so we cant have a solution