# Lab 1

#### Part A- Create a Notebook to demonstrate NumPy Operations.

In [1]:
# importing the numpy package
import numpy as np

1. <font color='blue'>Create an array that starts from the integer 1, ends at 20, incremented by 3. </font>

In [2]:
# Using arange function

# starting point = 1
# Ending point = 21 (excludes the number itself)
# steps = 3

arr1 = np.arange(1 ,21 , 3)
print(arr1)

[ 1  4  7 10 13 16 19]


2. <font color='blue'>Create a new array of shape 3 with random numbers between 0 and 1.</font>

In [3]:
# using np.random.random() function as its range is between 0 - 1
arr2= np.random.random([3])
print(arr2)

[0.18140291 0.85389875 0.64834365]


3. <font color='blue'>Create a 2 D array `[[10,20,45], [30,12,16], [42,17,56]]` and perform the following operations:
    - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.
    </font>

In [4]:
arr3= [
        [10,20,45], 
        [30,12,16], 
        [42,17,56]
    ]

*As the given np.array() is 2-D and the indexing starts from 0 we need to get `0th and 1st` sub array inorder to get the first to rows*

In [5]:
print(arr3[:2])

[[10, 20, 45], [30, 12, 16]]


Inorder to get the last two rows we have to methods either `reverse indexing` or else `simple indexing`

In [6]:
# Reverse indexing
print(arr3[-2:]) #recommended method as this is a robust method 

# simple indexing
print(arr3[1:])

[[30, 12, 16], [42, 17, 56]]
[[30, 12, 16], [42, 17, 56]]


4. <font color='blue'>Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.</font>

In [7]:
# creating a 2X2 matrix
arr4_1 = np.array([
            [0,1],
            [2,3]
        ])
arr4_2 = np.array([
    [1,3],
    [7,8],
])

In [8]:
# Vertical stacking

print(np.vstack([arr4_1,arr4_2])) 

[[0 1]
 [2 3]
 [1 3]
 [7 8]]


In [9]:
# Horizontal stacking
print(np.hstack([arr4_1,arr4_2])) 



[[0 1 1 3]
 [2 3 7 8]]


In [10]:
# splitting the array into subarrays
np.array_split(arr4_1,2)

[array([[0, 1]]), array([[2, 3]])]

 5. <font color='blue'>Create two matrices `X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),` 
	 - Is it possible to multiply these matrices? 
	 - Demonstrate the case when it is not possible to. </font>

In [11]:
#data
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

In [12]:
print(X.shape,Y.shape)

(3, 3) (3, 2)


<font color='green'>It is `possible` to multiply these matrix as the number of rows in `x` == number of columns in `y`.</font>

In [13]:
print(np.matmul(X,Y)) #Matrix multiplication of X and Y

[[70 28]
 [70 30]
 [60 26]]


**Making matrix where multiplication is `not possible`.**

In [14]:
X1 = np.array([
        [1,2],
        [3,4]
    ])
Y1 = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ])

In [15]:
print(X1.shape,Y1.shape)

(2, 2) (3, 3)


<font color='red'>It is `not possible` to multiply these matrix as the number of rows in `x` != number of columns in `y`.</font>

In [16]:
print(np.matmul(X1,Y1)) # error as matrix multiplication is not possible

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

 6. <font color='blue'>Create two arrays, `x = ([2, -1, -8]) y = ([3, 1, -2]),`
	 - Find the Shape, Number of dimensions of vector x.
	 - Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1). </font>

In [17]:
# data
x = np.array([2,-1,8])
y= np.array([3,1,-2])

- Using `np.ndim` inorder to find the dimensions of vector x


In [18]:
print(np.ndim(x))

1


- Using `np.reshape` to reshape the `x` of shape (3,1)

In [19]:
print(x.reshape(3,1))

[[ 2]
 [-1]
 [ 8]]


- Using the same for `y` inorder to *reshape* and *finding dimensions*

In [20]:
y = y.reshape(3,1) #reshaping

print(y.ndim) # Finding the dimensions

2


 7. <font color='blue'>How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix. </font>

#### `Working of Broadcasting`
- If the arrays don't have the same rank then prepend the shape of the lower rank array with 1s until both shapes have the same length.

**source:**<a href="https://www.geeksforgeeks.org/python-broadcasting-with-numpy-arrays/#:~:text=Broadcasting%20Rules%3A&text=If%20the%20arrays%20don't,size%201%20in%20that%20dimension.">GeekforGeeks</a>

In [21]:
# Generating a 3X3 matrix
arr5 = np.random.randint(1,10,[3,3])
arr5

array([[9, 7, 4],
       [2, 1, 7],
       [9, 5, 5]])

- `Subtraction` of the martix

In [22]:
print(arr5-10) # subtraction by single value (10)

[[-1 -3 -6]
 [-8 -9 -3]
 [-1 -5 -5]]


In [23]:
print(arr5 - [6,3,8]) # subtraction by columns

[[ 3  4 -4]
 [-4 -2 -1]
 [ 3  2 -3]]


In [24]:
print(arr5 - [[6],[3],[8]]) # subtraction by rows

[[ 3  1 -2]
 [-1 -2  4]
 [ 1 -3 -3]]


- `Multiplication` of matrix 

In [25]:
print(arr5*10) # multiplication by single value (10)

[[90 70 40]
 [20 10 70]
 [90 50 50]]


In [26]:
print(arr5 * [6,3,8]) # multiplication by columns

[[54 21 32]
 [12  3 56]
 [54 15 40]]


In [27]:
print(arr5 * [[6],[3],[8]]) # multiplication by rows

[[54 42 24]
 [ 6  3 21]
 [72 40 40]]


## Part B- Linear Equations

Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.

- Finding the singularity of the vector `X` by finding the determinant of the vector using `np.linalg.det`
 - If the determinant is not zero it is a `non-singular` vector and it is **<font color='green'>possible</font>** to slove the equation
 - If the determinant is zero it is a `singular` vector and it is **<font color='red'>not possible</font>** to slove the equation

### Part B.1

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

In [28]:
# making the vectors

X = np.array([
    [4,1,-2],
    [2,-3,2],
    [1,2,3]])
y = np.array([10,-4,6])

- Using `np.linalg.det` inorder to fing the singularity of `X`

In [29]:
print(np.linalg.det(X)) # As the determinant is not zero it is a non-singular matrix

-70.00000000000003


**<font color='green'>The equation is `solvable` as it is a `non-singular matrix`</font>**

- Using `np.linalg.solve` inorder to solve equation

In [30]:
print(np.linalg.solve(X,y))

[ 1.8  2.4 -0.2]


- `x` = **1.8**
- `y` = **2.4**
- `z` = **-0.2**

### Part B.2    		
1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [31]:
# Making the vectors
X1 = np.array([
    [2,-1,3,4],
    [4,-2,6,8],
    [3,1,2,-2],
    [1,3,-4,1]
])

y1 = np.array([10,20,3,-1])

- Using `np.linalg.det` inorder to fing the singularity of `X1`

In [32]:
print(np.linalg.det(X1)) # As the determinant is zero it is a non-singular matrix

0.0


**<font color='red'>The equation is `not solvable` as it is a `singular matrix`</font>**

- Using `np.linalg.solve` inorder to solve equation

In [33]:
print(np.linalg.solve(X1,y1)) #Showing an error as it is not possible to solve the equation

LinAlgError: Singular matrix