<h2><center>Lab 1 – Basic NumPy Operations</center><h2>
<h4><center>Submission by Chitrank Dave (8938766)</center></h4>

> ### **Part A- Create a Notebook to demonstrate NumPy Operations.**

In [19]:
import numpy as np

---
#### 1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [20]:
array = np.arange(1, 20, 3)
print("Result: ", array)

Result:  [ 1  4  7 10 13 16 19]


---
#### 2. Create a new array of shape 3 with random numbers between 0 and 1.

In [21]:
print(np.random.rand(3))

[0.88523193 0.4809034  0.16741977]


--- 
#### 3. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
* Slice the 2D array to get the first two rows.
* Slice the 2D array to get the last two rows.

In [22]:
arr = [10, 20, 45, 30, 12, 16, 42, 17, 56]
arr_2d = np.array(arr).reshape(3, 3)

print("Array: \n", arr_2d, "\n\n")

print("First 2 rows: \n", arr_2d[:2])

print("\n\nLast 2 rows: \n", arr_2d[-2:]) 

Array: 
 [[10 20 45]
 [30 12 16]
 [42 17 56]] 


First 2 rows: 
 [[10 20 45]
 [30 12 16]]


Last 2 rows: 
 [[30 12 16]
 [42 17 56]]


---
#### 4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [23]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1: \n", arr1)
print("\nArray 2: \n", arr2)

print("\n\nVertically Stacked: \n", np.vstack((arr1, arr2)))
print("\n\nHorizontally Stacked: \n", np.hstack((arr1, arr2)))

print("\n\nArray1 Split: \n", np.array_split(arr1, 2))
print("\nArray2 Split: \n", np.array_split(arr2, 2))



Array 1: 
 [[1 2]
 [3 4]]

Array 2: 
 [[5 6]
 [7 8]]


Vertically Stacked: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


Horizontally Stacked: 
 [[1 2 5 6]
 [3 4 7 8]]


Array1 Split: 
 [array([[1, 2]]), array([[3, 4]])]

Array2 Split: 
 [array([[5, 6]]), array([[7, 8]])]


--- 
#### 5. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]])
* Is it possible to multiply these matrices?
    - **Yes, it is possible to multiply the provided matrices since this dimensions of the matrix 1 is 3x3 and for matrix 2 is 2x3, and the requirement of matrices multiplication is that the number of columns in the first matrix equal the number of rows in the second matrix. The resulting product matrix will have the dimension of 3x2.**
* Demonstrate the case when it is not possible to.
    - **As mentioned above, matrix multiplication is only possible when the number of columns in the first matrix is equal to the number of rows in the second matrix. If this condition is not met, you cannot perform matrix multiplication. So, if we try to multiply provided second matrix with first matrix, then we can see the error thrown by the Python interpreter. (see the below outcome)**

In [24]:
m1 = [[5, 7, 2], [4, 5, 6], [7, 4, 2]]
m2 = [[4, 2], [6, 2], [4, 2]]

print("Matrix1: \n", m1)
print("\nMatrix2: \n", m2)

print("\n\nProduct of Matrix1 with Matrix2: \n", np.dot(m1, m2))
try:
    print("\n\nProduct of Matrix2 with Matrix1: \n", np.dot(m2, m1))
except:
    print("Matrices shapes are not aligned!!!")


Matrix1: 
 [[5, 7, 2], [4, 5, 6], [7, 4, 2]]

Matrix2: 
 [[4, 2], [6, 2], [4, 2]]


Product of Matrix1 with Matrix2: 
 [[70 28]
 [70 30]
 [60 26]]
Matrices shapes are not aligned!!!


---
#### 6. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2])
* Find the Shape, Number of dimensions of vector x.
* Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [25]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Array x: \n", x)
print("\nArray y: \n", y)

print("\n\nShape of x: ", x.shape)
print("Number of dimensions of x:", x.ndim)

Array x: 
 [ 2 -1 -8]

Array y: 
 [ 3  1 -2]


Shape of x:  (3,)
Number of dimensions of x: 1


In [26]:
x_reshaped = x.reshape((3, 1))
print("Vector x reshaped result: \n", x_reshaped)

y_reshaped = y.reshape((3, 1))
print("\nVector y reshaped result: \n", y_reshaped)
print("\nNumber of dimensions of vector y after reshaping to (3, 1): ", y_reshaped.ndim)

Vector x reshaped result: 
 [[ 2]
 [-1]
 [-8]]

Vector y reshaped result: 
 [[ 3]
 [ 1]
 [-2]]

Number of dimensions of vector y after reshaping to (3, 1):  2


---
#### 7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.
* **Broadcasting expands the smaller array to take the shape of the larger array.**

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([10, 11, 12])

print(a - 4)

print(a * 3)

print("\n\n Subtraction result of matrix b from a: \n", np.subtract(a, b))
print("\n\nMultiplication result of matrix a from b: \n", np.multiply(a, b))

[[-3 -2 -1]
 [ 0  1  2]
 [ 3  4  5]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


 Subtraction result of matrix b from a: 
 [[-9 -9 -9]
 [-6 -6 -6]
 [-3 -3 -3]]


Multiplication result of matrix a from b: 
 [[ 10  22  36]
 [ 40  55  72]
 [ 70  88 108]]


---
---

> ### **Part B- Linear Equations**

Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.


#### Part B.1
* 
    4x + y - 2z =  <br>
    2x - 3y + 2z = -4 <br>
    x + 2y + 3z = 6


In [28]:
def solveSystem(systemEqs, dependantEq):
  determination = np.linalg.det(systemEqs)
  print("Determinant: ", determination)
  if determination == 0:
    print("The system of equations is singular, hence it is")
  else:
    print("The system of equations is not singular.")
    print("The solution to the system of equations is: ", np.linalg.solve(systemEqs, dependantEq))

eqSystem = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])

solveSystem(eqSystem, np.array([10, -4, 6]))

Determinant:  -70.00000000000003
The system of equations is not singular.
The solution to the system of equations is:  [ 1.8  2.4 -0.2]


***Since the determinant of the coefficient matrix is not zero, the system of equations is not singular. This means that the system has a unique solution.***

---
#### Part B.2
*   2x - y + 3z + 4w = 10 <br>
    4x - 2y + 6z + 8w = 20 <br>
    3x + y - 2z + 2w = 3 <br>
    x + 3y - 4z + w = -1 <br>

In [29]:
eqSystem2 = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])

solveSystem(eqSystem2, np.array([10, 20, 3, 2]))

Determinant:  0.0
The system of equations is singular, hence it is


***Since the determinant of the coefficient matrix is zero, the system of equations is singular. This means that the system is unsolvable.***