# Lab 1 – Basic NumPy Operations
## Part A - Demonstration of Numpy Operations

In [10]:
import numpy as np

### 1. Creating an array that starts from the integer 1, ends at 20, incremented by 3.

In [11]:
array1 = np.arange(1, 20, 3)
print(f"Array 1: {array1}")

Array 1: [ 1  4  7 10 13 16 19]


### 2. Creating a new array of shape 3 with random numbers between 0 and 1.

In [12]:
array2 = np.random.rand(3)
print(f"Array 2: {array2}")

Array 2: [0.85066637 0.00299839 0.48111347]


### 3. Creating a 2D array [[10,20,45], [30,12,16], [42,17,56]] and performing the following operations:
##### Slicing the 2D array to get the first two rows, slicing the 2D array to get the last two rows.

In [13]:
array3 = np.array([[10,20,45], [30,12,16], [42,17,56]])
print(f"Array 3: {array3}\n")

# Slicing the 2D array to get the first two rows
print(f"First two rows: {array3[:2]}\n")

# Slicing the 2D array to get the last two rows
print(f"Last two rows: {array3[1:]}")

Array 3: [[10 20 45]
 [30 12 16]
 [42 17 56]]

First two rows: [[10 20 45]
 [30 12 16]]

Last two rows: [[30 12 16]
 [42 17 56]]


### 4. Creating two 2x2 arrays and demonstrating how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [14]:
array4 = np.array([[1,2], [3,4]])
array5 = np.array([[5,6], [7,8]])

print(f"Array 4: {array4}\n")
print(f"Array 5: {array5}\n")

# Stacking arrays vertically
print(f"Vertical stack: {np.vstack((array4, array5))}\n")

# Stacking arrays horizontally
print(f"Horizontal stack: {np.hstack((array4, array5))}\n")

# Splitting array into smaller array
print(f"Split array: {np.split(array4, 2)}")

Array 4: [[1 2]
 [3 4]]

Array 5: [[5 6]
 [7 8]]

Vertical stack: [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack: [[1 2 5 6]
 [3 4 7 8]]

Split array: [array([[1, 2]]), array([[3, 4]])]


### 5. Creating two matrices X=([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y=([[4, 2], [6, 2], [4, 2]]),
##### Is it possible to multiply these matrices?
##### Demonstrating the case when it is not possible to.

In [15]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

print(f"X: {X}\n")
print(f"Y: {Y}\n")

# Below is a case where it is possible to multiply the matrices.
print(f"Matrix multiplication: {np.matmul(X, Y)}\n")

# Below is a case where it is not possible to multiply the matrices.
print(f"Matrix multiplication: {np.matmul(Y, X)}")

X: [[5 7 2]
 [4 5 6]
 [7 4 2]]

Y: [[4 2]
 [6 2]
 [4 2]]

Matrix multiplication: [[70 28]
 [70 30]
 [60 26]]



ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

### 6. Creating two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
##### Finding the Shape, Number of dimensions of vector x.
##### Reshaping the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [16]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print(f"x: {x}\n")
print(f"y: {y}\n")

# Finding the shape of vector x
print(f"Shape of x: {x.shape}\n")

# Finding the number of dimensions of vector x
print(f"Number of dimensions of x: {x.ndim}\n")

# Reshaping vector x to a matrix of size (3,1)
x = x.reshape(3,1)
print(f"Reshaped x: {x}\n")

# Determining the number of dimensions after reshaping y to a matrix of (3,1)
y = y.reshape(3,1)
print(f"Reshaped y: {y}\n")

# Finding the number of dimensions of vector y
print(f"Number of dimensions of y: {y.ndim}")

x: [ 2 -1 -8]

y: [ 3  1 -2]

Shape of x: (3,)

Number of dimensions of x: 1

Reshaped x: [[ 2]
 [-1]
 [-8]]

Reshaped y: [[ 3]
 [ 1]
 [-2]]

Number of dimensions of y: 2


### 7. Showing how broadcasting work and demonstrating the subtraction, multiplication by considering a 3 x 3 matrix.

In [17]:
# Creating a 3 x 3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matrix: {matrix}\n")

# Subtracting 1 from each element in the matrix
print(f"Subtracting 1 from each element in the matrix: {matrix - 1}\n")

# Multiplying each element in the matrix by 2
print(f"Multiplying each element in the matrix by 2: {matrix * 2}")

Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtracting 1 from each element in the matrix: [[0 1 2]
 [3 4 5]
 [6 7 8]]

Multiplying each element in the matrix by 2: [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Part B - Linear Equations

##### Determining the singularity of the system of equations. Solving the system of equations if possible and justify the reason why the system can or cannot be solved using numpy functions.

##### Part B.1<br>4x + y - 2z = 10<br>2x - 3y + 2z = -4<br>x + 2y + 3z = 6

In [18]:
# Converting equation to matrix form
B1 = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])

# Finding the determinant of matrix B1
det_B1 = np.linalg.det(B1)

print("Determinant of B1:", det_B1)

Determinant of B1: -70.00000000000003


##### As the determinant of matrix B1 is not equal to zero, the matrix is nonsingular, and we can proceed to solve it using numpy functions. Let's find the solution to the equation.

In [19]:
b = np.array([10, -4, 6])
x = np.linalg.solve(B1, b)

print("Solution:", x)

Solution: [ 1.8  2.4 -0.2]


##### Part B.2<br>2x - y + 3z + 4w = 10<br>4x - 2y + 6z + 8w = 20<br>3x + y - 2z + 2w = 3<br>x + 3y - 4z + w = -1

In [20]:
# Converting equation to matrix form
B2 = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])

# Finding the determinant of matrix B2
det_B2 = np.linalg.det(B2)

print("Determinant of B2:", det_B2)

Determinant of B2: 0.0


##### As the determinant of matrix B2 is equal to zero, the matrix is singular, and it may have either no solution or infinitely many solutions.