## <center><b>PRACTICAL LAB 1: PART A</b>
<center> Done by Aardran Premakumar

#### <CENTER><B>PART A

<b>Question 1</b>
<br>Array starts from 1 and ends at 20 with 3 as increment.

In [1]:
#Array starts from 1 and ends at 20 with 3 as increment.
import numpy as np
arrElements = np.arange(start = 1, stop = 20, step = 3)
print(arrElements)

[ 1  4  7 10 13 16 19]


<b>Question 2</b>
<br>Array of shape 3 with random values between 0 and 1



In [2]:
#Array of shape 3 with random values between 0 and 1
randomArray = np.random.rand(3,3)
print(randomArray)

[[0.02808956 0.37791959 0.83021394]
 [0.35076163 0.07299535 0.59216716]
 [0.72916109 0.40317842 0.08731442]]


<b>Question 3</b>
<br>Creating 2D array and performing slice operation

In [3]:
#Creating 2D array and performing slice operation
list2D = [[10,20,45],[30,12,16],[42,17,56]]
num2D = np.array(list2D)
print("\n\n", num2D)

print("\n\n", num2D[:2:])

print("\n\n", num2D[1::])



 [[10 20 45]
 [30 12 16]
 [42 17 56]]


 [[10 20 45]
 [30 12 16]]


 [[30 12 16]
 [42 17 56]]


<b>Question 4</b>
<br>Vertical Stack, Horizontal Stack, Splitting Array

In [4]:
#Doing vertical stack, horizontal stack, splitting array into smaller ones.
array1 = np.arange(1,5).reshape(2,2)
array2 = np.arange(5,9).reshape(2,2)
print(array1, "\n", array2)
#vertical stack
vStack = np.vstack((array1, array2))
print("Vertical:\n " ,vStack)
#horizontal stack
hStack = np.hstack((array1,array2))
print("Horizontal:\n " ,hStack)
#splitting array into smaller arrays
array1Split = np.split(array1, 2, axis = 1)
array2Split = np.split(array2, 2, axis = 0)
print("Splitted first array\n", array1Split)
print("Splitted second array\n", array2Split)



[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]
Vertical:
  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal:
  [[1 2 5 6]
 [3 4 7 8]]
Splitted first array
 [array([[1],
       [3]]), array([[2],
       [4]])]
Splitted second array
 [array([[5, 6]]), array([[7, 8]])]


<b>Question 5</b>
<br>Matrix Multiplication

In [7]:
#Matrix Multiplication
X = np.array([[5,7,2],[4,5,6],[7,4,2]])
Y = np.array([[4,2],[6,2],[4,2]])
print("First matrix:\n",X)
print("Second matrix:\n",Y)
#It is possible to multiply the two matrices 
#since the size of the first matrix is in X * N and the size of the second matrix is in N * Y
matrixMultiplication = np.dot(X, Y)
print("Matrix after multiplication:\n",matrixMultiplication)

#For the case where the multiplication is not possible, the column size of 1st matrix is differ from the row size of 2nd matrix.
#Example
# matrixA = np.array([[4,5],[6,7]])
# matrixB = np.array([[1,2,3,], [4,5,6],[7,8,9]])




First matrix:
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
Second matrix:
 [[4 2]
 [6 2]
 [4 2]]
Matrix after multiplication:
 [[70 28]
 [70 30]
 [60 26]]


<b>Question 6</b>
<br>Finding shape and dimension of an array and re shaping the array.

In [20]:
#Finding shape and dimension of an array and re shaping the array.
arrayX = np.array([2,-1,-8])
arrayY = np.array([3,1,-2])

print("Array X:", arrayX)
print("Array Y:", arrayY)
#shape of array X
print("Shape of array X", arrayX.shape)
print("Dimension of vector X", arrayX.ndim)

reshapedArrayX = arrayX.reshape(3,1)
print("Array X reshaped:\n", reshapedArrayX)
print("Dimensions of array X after reshaping:\n", reshapedArrayX.ndim)
reshapedArrayY = arrayY.reshape(3,1)
print("Array Y reshaped:\n", reshapedArrayY)
print("Dimensional dimensions of array Y after reshaping:\n",reshapedArrayY.ndim)

Array X: [ 2 -1 -8]
Array Y: [ 3  1 -2]
Shape of array X (3,)
Dimension of vector X 1
Array X reshaped:
 [[ 2]
 [-1]
 [-8]]
Dimensions of array X after reshaping:
 2
Array Y reshaped:
 [[ 3]
 [ 1]
 [-2]]
Dimensional dimensions of array Y after reshaping:
 2


<b>Question 7</b>
<br>Broadcasting a 3x3 matrix with subtraction and multiplication.

<i>Broadcasting is a feature provided by NumPy, which allows to execute operations on arrays with different shapes. It adjusts the shape of the arrays to match with larger arrays, and do operations element-wise without changing the shape of the arrays.</i>

In [24]:
#Broadcasting a 3x3 matrix with subtraction and multiplication.
matrix3D = np.array([[10,20,30],[2,4,6],[11,12,13]])
subScalar = 5
mulScalar = 2
print("3x3 matrix: \n", matrix3D)
subbedMatrix3D = matrix3D - subScalar
print("Matrix after subtracting:\n", subbedMatrix3D)
mulMatrix3D = matrix3D * mulScalar
print("Matrix after multiplication:\n", mulMatrix3D)


3x3 matrix: 
 [[10 20 30]
 [ 2  4  6]
 [11 12 13]]
Matrix after subtracting:
 [[ 5 15 25]
 [-3 -1  1]
 [ 6  7  8]]
Matrix after multiplication:
 [[20 40 60]
 [ 4  8 12]
 [22 24 26]]
