In [3]:
# Name  - Aerish Gaba
# Student ID - 8949649

# array that starts from the integer 1, ends at 20, incremented by 3.
import numpy as np

array = np.arange(1, 21, 3)
print(array)

[ 1  4  7 10 13 16 19]


In [2]:
import numpy as np

# Create a new array of shape 3 with random numbers between 0 and 1
new_array = np.random.rand(3)

print(new_array)


[0.60234594 0.5057638  0.32085606]


In [4]:
import numpy as np

# Create a 2D array
array = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# Slice the 2D array to get the first two rows
first_two_rows = array[:2, :]
print("First two rows:")
print(first_two_rows)

# Slice the 2D array to get the last two rows
last_two_rows = array[1:, :]
print("Last two rows:")
print(last_two_rows)


First two rows:
[[10 20 45]
 [30 12 16]]
Last two rows:
[[30 12 16]
 [42 17 56]]


In [5]:
import numpy as np

# Create two 2x2 arrays
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

# Stacking vertically
vertical_stack = np.vstack((a1, a2))
print("Vertically stacked arrays:")
print(vertical_stack)

# Stacking horizontally
horizontal_stack = np.hstack((a1, a2))
print("Horizontally stacked arrays:")
print(horizontal_stack)

# Splitting smaller arrays
split_a1 = np.hsplit(a1, 2)
split_a2 = np.hsplit(a2, 2)
print("Split arrays:")
print(split_a1)
print(split_a2)


Vertically stacked arrays:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacked arrays:
[[1 2 5 6]
 [3 4 7 8]]
Split arrays:
[array([[1],
       [3]]), array([[2],
       [4]])]
[array([[5],
       [7]]), array([[6],
       [8]])]


In [15]:
import numpy as np

# Yes, Multiplication is possible as number of columns in X is equals to number of rows in Y
X= np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) 
Y= np.array([[4, 2], [6, 2], [4, 2]])

Z = np.matmul(X, Y)
print(Z)

# Case when it is not possible is when Y is multiplies by X as No of columns in Y is not equals to No of rows in X
# i.e. Z = np.matmul(Y, X) is not possible


[[70 28]
 [70 30]
 [60 26]]


In [23]:
import numpy as np

x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

shape_x = x.shape
dimensions_x = x.ndim

print("Shape of vector x:", shape_x)
print("Number of dimensions of vector x:", dimensions_x)

# Reshaping x to a matrix of size (3,1)
x_reshaped = x.reshape((3,1))

# Reshaping y to a matrix of size (3,1)
y_reshaped = y.reshape((3,1))

print(f"Number of dimensions of x after reshaping: {x_reshaped.ndim}")
print(f"Number of dimensions of y after reshaping: {y_reshaped.ndim}")





Shape of vector x: (3,)
Number of dimensions of vector x: 1
Number of dimensions of x after reshaping: 2
Number of dimensions of y after reshaping: 2


In [24]:
#The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
#Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

import numpy as np

# Create a 3 x 3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Subtract 2 from each element of the matrix
subtraction_result = matrix - 2

# Multiply each element of the matrix by 3
multiplication_result = matrix * 3

print("Subtraction Result:")
print(subtraction_result)

print("Multiplication Result:")
print(multiplication_result)


Subtraction Result:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
Multiplication Result:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [ ]:
|