In [1]:
import numpy as np
np.arange(1,21,3) 

array([ 1,  4,  7, 10, 13, 16, 19])

In [2]:
#q2
import numpy as np
r=np.random.rand(3)
print(r)

[0.28997164 0.56500299 0.71102785]


In [3]:
x=np.array([[10,20,45], [30,12,16], [42,17,56]])
print('first two rows',x[0:2])
print('last two rows',x[1:])


first two rows [[10 20 45]
 [30 12 16]]
last two rows [[30 12 16]
 [42 17 56]]


In [4]:
#q4
r=np.random.rand(2)
print(r)
p=np.random.rand(2)
print(p)
ver=np.vstack((r,p))
print(ver)
hor=np.hstack((r,p))
print(hor)


[0.21143289 0.98105876]
[0.01557859 0.52464195]
[[0.21143289 0.98105876]
 [0.01557859 0.52464195]]
[0.21143289 0.98105876 0.01557859 0.52464195]


In [5]:
#q6
x=np.array([2, -1, -8])
y=np.array([3, 1, -2])
print(x)
print(y)
xshape=x.shape
xdimension=x.ndim
print("xshape=",xshape)
print("xdim=",xdimension)

xreshape=x.reshape(3,1)
print('XRESHAPE',xreshape)

yshape=y.shape
ydimension=y.ndim
print("yshape=",yshape)
print("ydim=",ydimension)

yreshape=y.reshape(3,1)
print('yRESHAPE',yreshape)



[ 2 -1 -8]
[ 3  1 -2]
xshape= (3,)
xdim= 1
XRESHAPE [[ 2]
 [-1]
 [-8]]
yshape= (3,)
ydim= 1
yRESHAPE [[ 3]
 [ 1]
 [-2]]


In [6]:
#5
X= np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) 
Y= np.array([[4, 2], [6, 2], [4, 2]])
product=np.dot(X,Y)
print(product)
""" the above example wwas for 3x2 martixs so its possipble to do dot product
but if it was 2x3 matrix it was not possible to do so"""


[[70 28]
 [70 30]
 [60 26]]


' the above example wwas for 3x2 martixs so its possipble to do dot product\nbut if it was 2x3 matrix it was not possible to do so'

In [7]:
#7
A=np.random.randint(1,5,size=(3,3))


s=A-3
p=A+2
m=A*2
print("sub",s, "add ",p, "multi ",m, sep="\n\n")

sub

[[-2  0 -1]
 [ 0 -2 -1]
 [ 0 -2 -2]]

add 

[[3 5 4]
 [5 3 4]
 [5 3 3]]

multi 

[[2 6 4]
 [6 2 4]
 [6 2 2]]


In [8]:
#Part B
A = np.array([[4,1,-2],[2,-3,2],[1,2,3]])
det_A = np.linalg.det(A)
print('determinant of A',det_A)

B=np.array([10,-4,6])
x=np.linalg.solve(A,B)
print('Solution(x,y,z)',x)






determinant of A -70.00000000000003
Solution(x,y,z) [ 1.8  2.4 -0.2]


In [9]:
A = np.array([[2,-1,3,4],[4,-2,6,8],[3,1,-2,2],[1,3,-4,1]])
det_A = np.linalg.det(A)
print('determinant of A',det_A)



determinant of A 0.0
