In [1]:
import numpy as np


### PART A

1) Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
np.array([i for i in range(1, 21, 3)])

array([ 1,  4,  7, 10, 13, 16, 19])

2) Create a new array of shape 3 with random numbers between 0 and 1.

In [3]:
np.random.rand(3)

array([0.27986538, 0.57375456, 0.26114382])

3) Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [4]:
arr = [[10, 20, 45], [30, 12, 16], [42, 17, 56]]

In [5]:
arr[:2]

[[10, 20, 45], [30, 12, 16]]

In [6]:
arr[1:]

[[30, 12, 16], [42, 17, 56]]

4) Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [7]:
first_array = np.array([[10, 15],[20, 25]])
second_array = np.array([[11, 16],[21, 26]])

In [8]:
# Vertical Stacking
np.vstack((first_array, second_array))

array([[10, 15],
       [20, 25],
       [11, 16],
       [21, 26]])

In [9]:
# Horizontal Stacking
np.hstack((first_array, second_array))

array([[10, 15, 11, 16],
       [20, 25, 21, 26]])

In [10]:
# Splitting into smaller arrays
np.split(np.vstack((first_array, second_array)), 2)

[array([[10, 15],
        [20, 25]]),
 array([[11, 16],
        [21, 26]])]

5) Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
Is it possible to multiply these matrices?
Demonstrate the case when it is not possible to.

In [11]:
X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) 
Y= ([[4, 2], [6, 2], [4, 2]])

In [12]:
# Multiplying the two matrices
np.dot(X, Y)

array([[70, 28],
       [70, 30],
       [60, 26]])

6) Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
Find the Shape, Number of dimensions of vector x.
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [13]:
x = np.array([2, -1, -8]) 
y = np.array([3, 1, -2])

In [14]:
# Shape and Dimension of X
print('The Shape of X is :', x.shape)
print('The Dimension of X is :', x.ndim)

The Shape of X is : (3,)
The Dimension of X is : 1


In [15]:
# Reshaping X
x.reshape(3, 1)

array([[ 2],
       [-1],
       [-8]])

In [16]:
print('The Dimension of y after reshaping is :', y.reshape(3, 1).ndim)

The Dimension of y after reshaping is : 2


7) How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [17]:
arr = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

In [18]:
# Subracting on the Whole Array
arr - 2

array([[ 8, 18, 43],
       [28, 10, 14],
       [40, 15, 54]])

In [19]:
# Multiplying on the Whole Array
arr * 3

array([[ 30,  60, 135],
       [ 90,  36,  48],
       [126,  51, 168]])

### PART B

B.1) 4x + y - 2z = 10
    2x - 3y + 2z = -4
    x + 2y + 3z = 6

In [20]:
equation_array = np.array([[2,1,-2], [2, -3, 2], [1,2,3]])
right_side_array = np.array([10, -4, 6])

In [21]:
np.linalg.solve(equation_array, right_side_array)

array([ 2.86363636,  2.72727273, -0.77272727])

    B.2) Part B.2
        2x - y + 3z + 4w = 10
        4x - 2y + 6z + 8w = 20
        3x + y - 2z + 2w = 3
        x + 3y - 4z + w = -1

In [22]:
equation_array = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1,3,-4,1]])
right_side_array = np.array([10, 20, 3, -1])

In [23]:
# The matrix is singular in nature so we cannot use np to solve this equation
try:
    np.linalg.solve(equation_array, right_side_array)
except Exception as ex:
    print(ex)

Singular matrix
