Student Name: Parthasarathy Rajendiran <br>
Student ID: 8883828

# Lab 1 - Basic NumPy Operations

In [20]:
import numpy as np

## Part A - NumPy Operations

<font color = '#9C0006'> 1. Create an array that starts from the integer 1, ends at 20, incremented by 3. </font>

In [3]:
#1
array1 = np.arange(1, 20, 3)
array1

array([ 1,  4,  7, 10, 13, 16, 19])

<font color = '#9C0006'> 2. Create a new array of shape 3 with random numbers between 0 and 1. </font>

In [4]:
#2
array2 = np.random.rand(3)
print(array2)
print(array2.size)

[0.61862085 0.73856002 0.22938108]
3


<font color = '#9C0006'> 3. Create a 2 D array `[[10,20,45], [30,12,16], [42,17,56]]` and perform the following operations: 
	 - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows. </font>

In [5]:
#3
array3 = np.array([[10,20,45], [30,12,16], [42,17,56]])
print('The 2D array\n', array3)
print('First 2 rows')
print(array3[:2,])
print('Last 2 rows')
print(array3[-2:,])

The 2D array
 [[10 20 45]
 [30 12 16]
 [42 17 56]]
First 2 rows
[[10 20 45]
 [30 12 16]]
Last 2 rows
[[30 12 16]
 [42 17 56]]


<font color = '#9C0006'> 4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays. </font>

In [17]:
#4
array4 = (np.random.rand(4) * 10).astype(int).reshape(2, 2)
print('2x2 Array')
print(array4)

array4 = np.vstack((array4, array3[:1,:2]))
print('\nElements stacked horizontally to get 3x2 Array')
print(array4)

array4 = np.hstack((array4, array3[:,:1]))
print('\nElements stacked vertically')
print(array4)

print('\nThe array splitted to smaller subarrays')
print(np.array_split(array4, 3))

2x2 Array
[[0 0]
 [7 6]]

Elements stacked horizontally to get 3x2 Array
[[ 0  0]
 [ 7  6]
 [10 20]]

Elements stacked vertically
[[ 0  0 10]
 [ 7  6 30]
 [10 20 42]]

The array splitted to smaller subarrays
[array([[ 0,  0, 10]]), array([[ 7,  6, 30]]), array([[10, 20, 42]])]


<font color = '#9C0006'><pre> 5. Create two matrices `X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),` 
	 - Is it possible to multiply these matrices? 
	 - Demonstrate the case when it is not possible to. </pre></font>

In [22]:
#5
X= np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) 
Y= np.array([[4, 2], [6, 2], [4, 2]])

print(f'The shape of X is {X.shape} and Y is {Y.shape}')

The shape of X is (3, 3) and Y is (3, 2)


Since the number of columns of X is equal to number of rows of Y, it is possible to multiply X and Y

On the otherhand, Y * X is not possible as the number of columns of Y is not equal to number of rows of X

In [33]:
fmt = '{} * \n{}\n'
for matrix_tuple in [(X, Y), (Y, X)]:
    try:
        result = np.matmul(*matrix_tuple)
        print(fmt.format(*matrix_tuple) + '= \n', result)
    except ValueError as e:
        print(fmt.format(*matrix_tuple) + 'is not possible\nbecause of the exception \n' + str(e))
    finally:
        print('-' * 50)

[[5 7 2]
 [4 5 6]
 [7 4 2]] * 
[[4 2]
 [6 2]
 [4 2]]
= 
 [[70 28]
 [70 30]
 [60 26]]
--------------------------------------------------
[[4 2]
 [6 2]
 [4 2]] * 
[[5 7 2]
 [4 5 6]
 [7 4 2]]
is not possible
because of the exception 
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)
--------------------------------------------------


<font color = '#9C0006'><pre> 6. Create two arrays, `x = ([2, -1, -8]) y = ([3, 1, -2]),`
	 - Find the Shape, Number of dimensions of vector x.
	 - Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1). </pre></font>

In [44]:
#6
x = np.array([2, -1, -8]) 
y = np.array([3, 1, -2])

In [45]:
print('Shape of X is', x.shape)
print('Dimension of X is', x.ndim)

Shape of X is (3,)
Dimension of X is 1


In [47]:
x1 = x.reshape((3, 1))
y1 = y.reshape((3, 1))
print('Dimension of X is', x.ndim)
print('Dimension of Y is', y.ndim)

Dimension of X is 1
Dimension of Y is 1


<font color = '#9C0006'> 7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix. </font>

During arithmetic operations to an array with another smaller array or scalar, the smaller one is broadcasted (stretched) across the larger array such that they have the compatible shapes. This enables the numpy to do arithmetic operation element-by-element <br>
Reference: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [53]:
# Subtracting 
larger = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
smaller = np.array([1, 2, 3])
print('Larger Array\n', larger)
print('Smaller Array\n', smaller)

Larger Array
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
Smaller Array
 [1 2 3]


In [54]:
larger - smaller

array([[ 4,  5, -1],
       [ 3,  3,  3],
       [ 6,  2, -1]])

The smaller array of size 1X3 has been stretched to 3X3 such that the first column of larger array is subtracted by first element of smaller, second column of larger is subtracted by second element of the smaller and so on.

In [55]:
# Multiplication
larger * 2

array([[10, 14,  4],
       [ 8, 10, 12],
       [14,  8,  4]])

When multiplying a scalar value with an array, all the elements of the array got multiplied by the scalar

## Part B - Linear Equations

<font color = '#9C0006'>Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.</font>

The system of equations can be represented in matrix format (Ax = b) to check for the singularity and finding the solution. <br>
The matrix format of the equations can be easily translated to numpy arrays and using numpy.linalg, all the operations of linear algebra can be performed.

In [63]:
def is_singular(array):
    if array.shape[0] != array.shape[1]:
        return False  # As singular matrix should be a square matrix
    return np.linalg.det(array) == 0

In [66]:
x = ['x', 'y', 'z']

### Part B.1
<pre>
1. 4x +  y - 2z = 10 
2. 2x - 3y + 2z = -4 
3.  x + 2y + 3z =  6 
</pre>

In [73]:
A1 = np.array([
    [4, 1, -2],
    [2, -3, 2],
    [1, 2, 3]
])
b1 = np.array([10, -4, 6])

In [68]:
is_singular(A1)

False

The linear equations can be solved only if it is non-singular. Since A1 is non-singular, it is solvable. i.e., it has unique solution

In [74]:
soln1 = np.linalg.solve(A1, b1)

In [72]:
print('The solution of the B.1 is')
print(*[f'{var} = {val}' for var, val in zip(x, soln1)], sep='\n')

The solution of the B.1 is
x = 1.7999999999999998
y = 2.4
z = -0.2


### Part B.2

<pre>
1. 2x -  y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x +  y - 2z + 2w =  3
4.  x + 3y - 4z +  w = -1
</pre>

In [75]:
A2 = np.array([
    [2, -1, 3, 4],
    [4, -2, 6, 8],
    [3, 1, -2, 2],
    [1, 3, -4, 1]
])
b2 = np.array([10, 20, 3, -1])

In [76]:
is_singular(A2)

True

The B.2 set of equations can not be solved. <br>
As this is singular, these equations has no or infinite solutions.