## Part A - Arsalan Shoaib Patel
### Question 1
Arange gives the array from (x1 to x2 with step size x3) with the argument being arange(x1,x2,x3)


In [97]:
import numpy as np
a1= np.arange(1,21,3)
print(a1)


[ 1  4  7 10 13 16 19]


### Question 2
rand gives x(argument) amount of numbers between 0 and 1

In [98]:
shape3array = np.random.rand(3)
print(shape3array)

[0.3769218  0.80350287 0.74843086]


### Question 3

In [99]:
TwoD_Array = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("First two Rows\n", TwoD_Array[:2, :])
print("Last two Rows\n", TwoD_Array[1:, :])

First two Rows
 [[10 20 45]
 [30 12 16]]
Last two Rows
 [[30 12 16]
 [42 17 56]]


### Question 4

In [100]:

a1 = np.array([[1, 1], 
            [3, 5]])
a2 = np.array([[9, 6],
            [12, 4]])

print("Vertical Stack:\n", np.vstack((a1,a2)))
print("Horizontal Stack:\n", np.hstack((a1,a2)))

print("Split in smaller vertical arrays:\n")
Vstack= np.vstack((a1,a2))
VSplit = np.split(Vstack, 2)
for i in VSplit:
    print(i)

Vertical Stack:
 [[ 1  1]
 [ 3  5]
 [ 9  6]
 [12  4]]
Horizontal Stack:
 [[ 1  1  9  6]
 [ 3  5 12  4]]
Split in smaller vertical arrays:

[[1 1]
 [3 5]]
[[ 9  6]
 [12  4]]


### Question 5

Dot product is possible when you multiply X * Y but not possible if you put multiply Y * X 

In [101]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])


print("Dot product possible when X * Y)", np.dot(X,Y))
#It is not possbible when you multiply Y * X
try:
    dotYX = np.dot(Y,X)
except ValueError as error:
    dotYX = str(error)
print("Multiply the Y and X\n", dotYX)


Dot product possible when X * Y) [[70 28]
 [70 30]
 [60 26]]
Multiply the Y and X
 shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)


### Question 6

In [102]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])


print("Shape of x:", x.shape) #x.shape gives shape
print("Number of dimensions of x:", x.ndim) #.ndim gives dimensions

reshapeX= x.reshape((3,1))
reshapeY= y.reshape((3,1))
print("Number of dimensions of Y after reshaping to a matrix(3,1):", reshapeY.ndim)

Shape of x: (3,)
Number of dimensions of x: 1
Number of dimensions of Y after reshaping to a matrix(3,1): 2


### Question 7

In [103]:
matrixA = np.array([[2,2,2],
                    [4,4,4],
                    [6,6,6]])
array = np.array([1,2,3])
matrixB = np.array([[2,2,2],[4,4,4]])
#subtraction by subtracting a scalar number from a matrix, using broadcasting
sub = matrixA - 2
print("Subtraction\n", sub)

#Showing when multiplication is possible using broadcasting using two matrixes 
MatA_By_array = matrixA * array
print("Multiply the A and array \n", MatA_By_array)

#showing where broadcasting cant be done because of matrix sizes being different
try:
    matAmatB = matrixA * matrixB 
except ValueError as error:
    matAmatB = str(error)
print("Multiply the A and B\n", matAmatB)

Subtraction
 [[0 0 0]
 [2 2 2]
 [4 4 4]]
Multiply the A and array 
 [[ 2  4  6]
 [ 4  8 12]
 [ 6 12 18]]
Multiply the A and B
 operands could not be broadcast together with shapes (3,3) (2,3) 
