## PartB - Arsalan Shoaib Patel
### B1
There is no linear dependence seen in these equations hence it is not singular with the matrix being non full rank. When numpy calculates the determinant of the matrix it will be non zero meaning it has a unique solution. Hence this can be solved by numpy 

In [1]:
import numpy as np
x=np.array([[4, 1, -2],
            [2, -3, 2],
            [1, 2, 3]])

y=np.array([10, -4, 6])

matrix= np.column_stack((x,y))
print("Matrix by coefficients:\n", matrix)

if (np.linalg.det(x)!=0): #means the system is non singular and has a unique solution
    print("\nthis system is non singular and has a unique solution")
    m= np.linalg.solve(x, y)
    print("unique solution:",[[m[0]],
                             [m[1]],
                             [m[2]]])
else:
    print("\nThe system is singular, and there is no unique solution.")


Matrix by coefficients:
 [[ 4  1 -2 10]
 [ 2 -3  2 -4]
 [ 1  2  3  6]]

this system is non singular and has a unique solution
unique solution: [[1.7999999999999998], [2.4], [-0.2]]


### B2
There is linear dependence seen in these equations hence it is singular with the matrix being full rank. When numpy calculates the determinant of the matrix it will be  zero meaning it has no unique solutions. Hence this can not be solved by numpy 

In [2]:
x=np.array([[2, -1, 3, 4],
              [4, -2, 6, 8],
              [3, 1, -2, 2],
              [1, 3, -4, 1]])


y=np.array([10, 20, 3, -1])
matrix= np.column_stack((x,y))
print("Matrix by coefficients:\n", matrix)
if (np.linalg.det(x)!=0): #means the system is non singular and has a unique solution
    print("This system is non singular and has a unique solution")
    m= np.linalg.solve(x, y)
    print("unique solution:",[[m[0]],
                             [m[1]],
                             [m[2]]])
else:
    print("The matrix's determinant is zero")
    print("\nThe system is singular, and there is no unique solution.")



Matrix by coefficients:
 [[ 2 -1  3  4 10]
 [ 4 -2  6  8 20]
 [ 3  1 -2  2  3]
 [ 1  3 -4  1 -1]]
The matrix's determinant is zero

The system is singular, and there is no unique solution.
