In [1]:
#Question 1
import numpy as np

# Create the array
my_array = np.arange(1, 21, 3)

# Print the array
print(my_array)


[ 1  4  7 10 13 16 19]


This array starts at 1, ends at 20, and is incremented by 3, as required.

In [2]:
#Question 2
import numpy as np

# Create a random array of shape (3,) with numbers between 0 and 1
random_array = np.random.rand(3)

# Print the random array
print(random_array)


[0.65932488 0.87785038 0.32768556]


This array generates different random numbers between 0 and 1 each time it's run.

In [3]:
#Question 3
import numpy as np

# Create the 2D array
my_2d_array = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# Slice the first two rows
first_two_rows = my_2d_array[:2, :]

# Slice the last two rows
last_two_rows = my_2d_array[1:, :]

# Print the results
print("Original 2D Array:")
print(my_2d_array)

print("\nFirst Two Rows:")
print(first_two_rows)

print("\nLast Two Rows:")
print(last_two_rows)


Original 2D Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

First Two Rows:
[[10 20 45]
 [30 12 16]]

Last Two Rows:
[[30 12 16]
 [42 17 56]]


In this code, a 2D NumPy array my_2d_array with the specified values was created. my_2d_array[:2, :] was used to slice the first two rows, where :2 specifies the first two rows, and : includes all columns. To slice the last two rows, my_2d_array[1:, :] was used, where 1: specifies all rows from the second row onward, and : includes all columns.

In [4]:
#Question 4
import numpy as np

# Create two 2x2 arrays
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

# Stack the arrays vertically
vertical_stack = np.vstack((array1, array2))

# Stack the arrays horizontally
horizontal_stack = np.hstack((array1, array2))

# Split the combined array back into smaller arrays
split_vertical = np.split(vertical_stack, 2)
split_horizontal = np.split(horizontal_stack, 2, axis=1)

# Print the original arrays and the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nStacked Vertically:")
print(vertical_stack)

print("\nStacked Horizontally:")
print(horizontal_stack)

print("\nSplit Vertically:")
for subarray in split_vertical:
    print(subarray)

print("\nSplit Horizontally:")
for subarray in split_horizontal:
    print(subarray)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Stacked Vertically:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Stacked Horizontally:
[[1 2 5 6]
 [3 4 7 8]]

Split Vertically:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

Split Horizontally:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


Arrrays can be stack both vertically and horizontally, and then split back into smaller arrays as needed using NumPy functions.

In [5]:
#Question 5
import numpy as np

# Define matrices X and Y
X = np.array([[5, 7, 2],
              [4, 5, 6],
              [7, 4, 2]])

Y = np.array([[4, 2],
              [6, 2],
              [4, 2]])

# Attempt matrix multiplication
try:
    result = np.dot(X, Y)
    print("Result of Matrix Multiplication:")
    print(result)
except ValueError as e:
    print(f"Matrix multiplication is not possible: {e}")

# Demonstrate a case where multiplication is not possible
Z = np.array([[4, 2, 1],
              [6, 2, 5]])

try:
    result = np.dot(X, Z)
    print("Result of Matrix Multiplication:")
    print(result)
except ValueError as e:
    print(f"Matrix multiplication is not possible: {e}")


Result of Matrix Multiplication:
[[70 28]
 [70 30]
 [60 26]]
Matrix multiplication is not possible: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)


This code first performs matrix multiplication for matrices X and Y (which is possible), and then it demonstrates a case with matrices X and Z (where multiplication is not possible).

In [6]:
#Question 6
import numpy as np

# Create the arrays
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Find the shape and number of dimensions of vector x
x_shape = x.shape
x_dimensions = x.ndim

# Reshape vector x to a matrix of size (3,1)
x_reshaped = x.reshape((3, 1))

# Determine the number of dimensions after reshaping vector y to a matrix of size (3,1)
y_reshaped = y.reshape((3, 1))
y_dimensions_after_reshape = y_reshaped.ndim

# Print the results
print("Vector x:")
print("Shape:", x_shape)
print("Number of dimensions:", x_dimensions)

print("\nReshaped Vector x:")
print(x_reshaped)

print("\nReshaped Vector y:")
print(y_reshaped)
print("Number of dimensions after reshaping y:", y_dimensions_after_reshape)


Vector x:
Shape: (3,)
Number of dimensions: 1

Reshaped Vector x:
[[ 2]
 [-1]
 [-8]]

Reshaped Vector y:
[[ 3]
 [ 1]
 [-2]]
Number of dimensions after reshaping y: 2


The original vector x has a shape of (3,) and 1 dimension. After reshaping x to a matrix of size (3,1), it becomes a 2D array. Vector y is also reshaped to a matrix of size (3,1), which results in a 2D array with 2 dimensions.

In [7]:
#Question 7
import numpy as np

# Create a 3x3 matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Subtract a scalar (e.g., 2) from every element of the matrix
result_subtract = A - 2

# Multiply every element of the matrix by a scalar (e.g., 3)
result_multiply = A * 3

# Print the results
print("Original Matrix A:")
print(A)

print("\nSubtract 2 from every element:")
print(result_subtract)

print("\nMultiply every element by 3:")
print(result_multiply)


Original Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtract 2 from every element:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Multiply every element by 3:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


Broadcasting is a powerful feature in NumPy that allows for element-wise operations between arrays of different shapes, as long as certain compatibility rules are met. These rules allow NumPy to implicitly expand smaller arrays to match the shape of larger arrays, making operations more flexible and efficient. Broadcasting is particularly useful when working with arrays of different shapes in mathematical operations like addition, subtraction, multiplication, etc.

As you can see, broadcasting allows us to perform element-wise subtraction and multiplication between the matrix and scalars without explicitly creating a matching-shaped scalar array. NumPy automatically handles the broadcasting to make the operations work seamlessly.