# <center>  Lab 1 – Basic NumPy Operations<center>
---
Student Name: **Devarsh Sandip Shah** <br>
Student ID: **8917026**

## Part A- Create a Notebook to demonstrate NumPy Operations.

<span style="color:orange">1] Create an array that starts from the integer 1, ends at 20, incremented by 3.</span>

In [1]:
import numpy as np
nums=np.arange(1,20,3)
print("Array from 1 to 20 incremented by 3 are : ", nums)

Array from 1 to 20 incremented by 3 are :  [ 1  4  7 10 13 16 19]


<span style="color:orange">2] Create a new array of shape 3 with random numbers between 0 and 1.</span>

In [2]:
random_nums=np.random.rand(3)
print(random_nums)

[0.82698864 0.06750584 0.26329166]


<span style="color:orange">3] Create a 2 D array `[[10,20,45], [30,12,16], [42,17,56]]` and perform the following operations: 
 - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.</span>

In [3]:
# Array Created
arr3 = np.array([[10,20,45], [30,12,16], [42,17,56]])

# Slicing of Array
print("First 2 rows:\n",arr3[:2])
print("Last 2 rows:\n",arr3[1:])

First 2 rows:
 [[10 20 45]
 [30 12 16]]
Last 2 rows:
 [[30 12 16]
 [42 17 56]]


<span style="color:orange">4] Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.</span>

In [4]:
# Two 2x2 arrays
arr4a = np.array([[1, 2], [3, 4]])
arr4b = np.array([[5, 6], [7, 8]])
print("\nArray 4a:")
print(arr4a)
print("\nArray 4b:")
print(arr4b)

# vertically Stacked
stacked_vertically = np.vstack((arr4a, arr4b))
print("\nStacked vertically:")
print(stacked_vertically)

# horizontally Stacked
stacked_horizontally = np.hstack((arr4a, arr4b))
print("\nStacked horizontally:")
print(stacked_horizontally)

# Split into smaller arrays
split_arrays = np.split(stacked_horizontally, 2)
print("\nSplited Smaller Arrays:")
print(split_arrays)



Array 4a:
[[1 2]
 [3 4]]

Array 4b:
[[5 6]
 [7 8]]

Stacked vertically:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Stacked horizontally:
[[1 2 5 6]
 [3 4 7 8]]

Splited Smaller Arrays:
[array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]


<span style="color:orange">5] Create two matrices `X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),` 
- Is it possible to multiply these matrices? 
 <br> **Answer**: A matrix of shape (m, n) can be multiplied with a matrix of size (p,q) if and only if n and p are equal, then the shape of the resultant matrix will be (m,q). In the given example of X is a matrix of shape (3,3) and Y is of shape (3,2), Thus, number of columns of X is equal to number of rows of Y. Thus it is possible to multiply x with Y. The resultant matrix will be of size (3,2). But the reverse is not possible i.e. (2,3)

- Demonstrate the case when it is not possible to.
 <br>**Answer:** When we try to multiply Y with X, we can't multiply. Both examples are demonstrated below.</span>

In [5]:
# Two Matrices X(3,3) and Y(3,2)
X=np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y=np.array([[4, 2], [6, 2], [4, 2]])

# Multiplying X*Y
if(X.shape[1]==Y.shape[0]):
    print("=> X * Y \n",np.matmul(X,Y))
else:
    print("Not possible to multiply X * Y")
    print("The number of columns of X is not equal to the row of Y")
    
# Multiplying Y*X
if(Y.shape[1]==X.shape[0]):
    print("=> Y * X  \n",np.matmul(Y,X))
else:
    print("Not possible to multiply Y * X")
    print("The number of columns of Y is not equal to the row of X")

=> X * Y 
 [[70 28]
 [70 30]
 [60 26]]
Not possible to multiply Y * X
The number of columns of Y is not equal to the row of X


<span style="color:orange">6] Create two arrays, `x = ([2, -1, -8]) y = ([3, 1, -2]),`
- Find the Shape, Number of dimensions of vector x.
- Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).</span>

In [6]:
#Two Arrays
X=np.array([2, -1, -8])
Y=np.array([3, 1, -2])

# Shape of Arrays
print("Shape of X=",X.shape)
print("Shape of Y=",Y.shape)

# Dimension of X
print("Dimension of vector X=",X.ndim)

# Reshape X and Y to (3, 1) matrix
x_reshaped = X.reshape((3, 1))
y_reshaped = Y.reshape((3, 1))
print("\nReshaped X:")
print(x_reshaped)
print("\nReshaped Y:")
print(y_reshaped)
print("Number of dimensions after reshaping Y:", y_reshaped.ndim)

Shape of X= (3,)
Shape of Y= (3,)
Dimension of vector X= 1

Reshaped X:
[[ 2]
 [-1]
 [-8]]

Reshaped Y:
[[ 3]
 [ 1]
 [-2]]
Number of dimensions after reshaping Y: 2


<span style="color:orange">7] How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.</span>
<br>**Answer :** Broadcasting in NumPy refers to its capability to handle arrays with varying shapes for arithmetic operations. Arrays are considered compatible for broadcasting if they share the same size or if one of them has a size of one. 

In [7]:
# One 3x3 matrix
mat7 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatrix 7:")
print(mat7)

# Subtract 1 from all elements using broadcasting
subtracted_matrix = mat7 - 1
print("\nResult of subtraction:")
print(subtracted_matrix)

# Multiply by 2 using broadcasting
multiplicated_matrix = mat7 * 2
print("\nResult of multiplication:")
print(multiplicated_matrix)



Matrix 7:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result of subtraction:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Result of multiplication:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


---
## Part B- Linear Equations
Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.
### <span style="color:orange">Part B.1</span>

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

<span style="color:green">Answer:</span>
==> To determine singularity, we can check if the determinant of the coefficient matrix. If the determinant is zero, the system is singular, and there may be either no solutions or infinitely many solutions.

Let's calculate the determinant and solve the system:

In [8]:
coefficient_matrix=np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])
right_hand_side_vector=np.array([10,-4,6])

#Calculate determinant of the coefficient matrix
det_matrix = np.linalg.det(coefficient_matrix)

if det_matrix==0:
    print("The system is singular, and there may be no solutions or infinitely many solutions.")
else:
    #if it is a non-singular system then Solve it
    print("It is a Non- singular System:")
    resultant_matrix=np.linalg.solve(coefficient_matrix,right_hand_side_vector)
    print("Solution of x, y, and z :",resultant_matrix)


It is a Non- singular System:
Solution of x, y, and z : [ 1.8  2.4 -0.2]


### <span style="color:orange">Part B.2</span>
1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [9]:
# Coefficient matrix
coefficient_matrix = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])

# Right-hand side vector
right_hand_side_vector = np.array([10, 20, 3, -1])

# Calculate the determinant
det_matrix = np.linalg.det(coefficient_matrix)

if det_matrix == 0:
    print("The system is singular, and there may be no solutions or infinitely many solutions.")
else:
    # if it is a non-singular System then Solve it
    resultant_matrix = np.linalg.solve(coefficient_matrix, right_hand_side_vector)
    print("Solution for x, y, z, and w:")
    print(resultant_matrix)


The system is singular, and there may be no solutions or infinitely many solutions.
