# Lab 1

## Lab 1 – Basic NumPy Operations


In [2]:
# Importing the package

import numpy as np

#### 1.  Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [3]:
# create array from 1 to 20 with 3 intervals between them

array1D = np.arange(1, 20, 3)
print(array1D)

[ 1  4  7 10 13 16 19]


### 2. Create a new array of shape 3 with random numbers between 0 and 1.

In [62]:
arr_rand = np.random.rand(10)
# print(arr_rand)
arr_rand.shape

[0.55224242 0.62902572 0.57929568 0.11494719 0.68380816 0.87608212
 0.66400914 0.90230059 0.70464356 0.19455448]


(10,)

#### 3. Create a 2 D array `[[10,20,45], [30,12,16], [42,17,56]]` and perform the following operations: 
	 - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [5]:
array2D = np.array([[10,20,45],[30,12,16],[42,17,56]])
# print(array2D)


# to get first 2 row of the 2 dimension array

array2d_first_2row = array2D[:2, :]
print(array2d_first_2row)


# to get last two row of the 2D array

array2d_last_2row = array2D[-2:,:]
print(array2d_last_2row)





[[10 20 45]
 [30 12 16]]
[[30 12 16]
 [42 17 56]]


#### 4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [70]:
array_1 = np.random.randint(50, size = (2,2))
array_2 = np.random.randint(50, size = (2,2))

# print(array_1,'\n\n',array_2)

# Horizontally stack of matrix
array_horizontal_stack = np.stack([array_1, array_2], axis=0)

# Vertically stack of matrix
array_vertical_stack = np.stack([array_1, array_2], axis=1)


#split the array
array_split = np.split(array_1, 2, axis=0)  
print("Splited array",array_split)

print("\n\n")

print("Horizontal stacked of matrix \n", array_horizontal_stack,'\n\n\n Vertical stack of matrix \n',array_vertical_stack)



Splited array [array([[32,  4]]), array([[19, 17]])]



Horizontal stacked of matrix 
 [[[32  4]
  [19 17]]

 [[ 0 48]
  [13  0]]] 


 Vertical stack of matrix 
 [[[32  4]
  [ 0 48]]

 [[19 17]
  [13  0]]]


## 5.

In [12]:
#creating two matrices

matrix_X = np.array([[5,7,2],[4,5,6],[7,4,2]])
matrix_Y = np.array([[4,2],[6,2],[4,2]])

print(matrix_X,'\n', matrix_Y)





# performing matrix multiplication 
matrix_mult = np.matmul(matrix_X,matrix_Y)

#- Is it possible to multiply these matrices? 

# Yes matrix multiplication "X.Y"  is possible since first matrix column is equal to second nos of column

print(matrix_mult)


[[5 7 2]
 [4 5 6]
 [7 4 2]] 
 [[4 2]
 [6 2]
 [4 2]]
[[70 28]
 [70 30]
 [60 26]]


### - Demonstrate the case when it is not possible to.
##### If first matrix's column is not equal to second matrix's row than matrix multiplication is not possible. Matrix multiplication of X and Y is possible but matrix muliplication of Y and X is not possible

In [13]:
matrix_mult_Y.X = np.matmul(matrix_Y,matrix_X)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

 ## 6. 

In [46]:
# Creating two arrays, `x = ([2, -1, -8]) y = ([3, 1, -2]),`

vector_X = np.array([2,-1,-8])
vector_y = np.array([3,1,-2])

print(vector_X,vector_y)

# Shape , number of dimension of vector x
shape_X = vector_X.shape
dimension_Y = vector_X.ndim
size_x = vector_X.size
print('Shape of x :', shape_X, 'Deimension of vectorx',dimension_X,"and size is :", size_x)

# Reshape to (3,1)
reshape_X = vector_X.reshape(3,1)
print('Reshape of x :', reshape_X)

# Reshape of y vector in (3,1)
reshape_Y = vector_y.reshape(3,1)
shape_Y = reshape_Y.shape
dimension_Y = reshape_Y.ndim
print('Reshape shape of vector y -->', reshape_Y, "and dimension of reshaped Y is :", dimension_Y)



[ 2 -1 -8] [ 3  1 -2]
Shape of x : (3,) Deimension of vectorx (3,) and size is : 3
Reshape of x : [[ 2]
 [-1]
 [-8]]
Reshape shape of vector y --> [[ 3]
 [ 1]
 [-2]] and dimension of reshaped Y is : 2


###  7.

In [57]:
# creating 3*3 matrices

matrix_3_X = np.random.randint(10, size=(3, 3))
matrix_3_y = np.random.randint(10,size=(3,3))

# print(matrix_3_X)
# print(matrix_3_y)


# substraction of matrix
sub_matrix = (matrix_3_X - matrix_3_y)

# Addition of matrix
add_matrix = (matrix_3_X + matrix_3_y)

# Multiplication pf matrix
mult_matrix = np.matmul(matrix_3_X, matrix_3_y)



print ("Sub = ", sub_matrix , '\n Addition = ', add_matrix,'\n multiplication = ', mult_matrix)






Sub =  [[-1 -1  1]
 [ 1 -8 -2]
 [-5  8 -5]] 
 Addition =  [[ 1  9  1]
 [13  8  8]
 [13 10  7]] 
 multiplication =  [[33 33 26]
 [34 38 18]
 [67 93 51]]
[[0 4 1]
 [7 0 3]
 [4 9 1]]
[[1 5 0]
 [6 8 5]
 [9 1 6]]
[[-1 -1  1]
 [ 1 -8 -2]
 [-5  8 -5]]
